/**
 * The generated workflow function body.
 *
 * Decides the text between the body markers inside the workflow function:
 * the body generator's output for the workflow, indented one level under a
 * do-not-edit banner. A function without markers has its whole body replaced
 * by the marked section; a function with markers has only the marked text
 * replaced, so anything the author wrote outside the markers stays.
 */

import type { TWorkflowAST } from '../../ast/types';
import { bodyGenerator } from '../../generator/body-generator';
import type { GraphIdentityStamp } from '../../generator/unified';
import { MARKERS } from '../../parser/generated-sections';
import { type SourceEdit, findFunctionDeclaration, parseSource } from './source-file';

/**
 * Generate the workflow function body
 */
export function generateFunctionBody(
  ast: TWorkflowAST,
  production: boolean,
  isAsync: boolean,
  durableSequential: boolean,
  identity?: GraphIdentityStamp,
): string {
  const lines: string[] = [];

  lines.push('  // ============================================================================');
  lines.push('  // DO NOT EDIT - This section is auto-generated by Flow Weaver');
  lines.push('  // Edit the @flowWeaver annotations above to modify workflow behavior');
  lines.push('  // ============================================================================');
  lines.push('');

  // Get the generated body from existing body generator
  const body = bodyGenerator.generateWithExecutionContext(
    ast,
    ast.nodeTypes,
    isAsync, // Respect original function's async/sync nature
    production,
    false,
    durableSequential,
    identity,
  );

  // Add proper indentation
  const indentedBody = body
    .split('\n')
    .map((line) => (line.trim() ? '  ' + line : line))
    .join('\n');

  lines.push(indentedBody);

  return lines.join('\n');
}

/**
 * Replace the body of a workflow function with generated code
 */
export function replaceWorkflowFunctionBody(
  source: string,
  functionName: string,
  newBody: string
): SourceEdit {
  const functionNode = findFunctionDeclaration(parseSource(source), functionName);

  if (!functionNode || !functionNode.body) {
    return { code: source, changed: false };
  }

  // Check if body already has markers
  const bodyText = source.slice(functionNode.body.pos, functionNode.body.end);

  const bodyStartMarkerIdx = bodyText.indexOf(MARKERS.BODY_START);
  const bodyEndMarkerIdx = bodyText.indexOf(MARKERS.BODY_END);

  if (bodyStartMarkerIdx !== -1 && bodyEndMarkerIdx !== -1) {
    // Replace content between body markers
    const absoluteBodyStart =
      functionNode.body.pos + bodyStartMarkerIdx + MARKERS.BODY_START.length;
    const absoluteBodyEnd = functionNode.body.pos + bodyEndMarkerIdx;

    const before = source.slice(0, absoluteBodyStart);
    const after = source.slice(absoluteBodyEnd);

    const newCode = before + '\n' + newBody + '\n  ' + after;

    // Check if content changed
    const originalBody = source.slice(absoluteBodyStart, absoluteBodyEnd);
    const changed = originalBody.trim() !== newBody.trim();

    return { code: newCode, changed };
  }

  // No markers in body - insert them
  // Find the opening brace of the function body
  const openBraceIdx = source.indexOf('{', functionNode.body.pos);
  if (openBraceIdx === -1) {
    return { code: source, changed: false };
  }

  // Find the closing brace
  const closeBraceIdx = functionNode.body.end - 1;
  if (closeBraceIdx <= openBraceIdx) {
    return { code: source, changed: false };
  }

  const before = source.slice(0, openBraceIdx + 1);
  const after = source.slice(closeBraceIdx);

  const newBodyWithMarkers = [
    '',
    '  ' + MARKERS.BODY_START,
    newBody,
    '  ' + MARKERS.BODY_END,
    '',
  ].join('\n');

  return {
    code: before + newBodyWithMarkers + after,
    changed: true,
  };
}
