/**
 * The inlined runtime section.
 *
 * Decides what goes between the runtime markers and where that section sits:
 * the whole runtime is always inlined (a compiled workflow has no runtime
 * dependency), and a file compiled for the first time gets the section right
 * after its last import. On a recompile only the text between the markers is
 * replaced.
 */

import * as ts from 'typescript';
import { MARKERS } from '../../parser/generated-sections';
import { generateInlineRuntime } from '../inline-runtime';
import { type SourceEdit, parseSource } from './source-file';

/**
 * Write the runtime section for `production` (or development) between the
 * runtime markers, inserting the markers after the imports when absent.
 */
export function replaceOrInsertRuntimeSection(source: string, production: boolean): SourceEdit {
  return replaceOrInsertSection(
    source,
    MARKERS.RUNTIME_START,
    MARKERS.RUNTIME_END,
    generateRuntimeSection(production)
  );
}

/**
 * Generate the runtime section content that goes between the markers.
 * Runtime is always inlined — zero runtime dependencies.
 */
function generateRuntimeSection(production: boolean): string {
  const lines: string[] = [];

  lines.push('// ============================================================================');
  lines.push('// DO NOT EDIT - This section is auto-generated by Flow Weaver');
  lines.push('// ============================================================================');
  lines.push('');

  lines.push(generateInlineRuntime(production));

  return lines.join('\n');
}

/**
 * Replace content between markers, or insert the markers after the imports if they don't exist
 */
function replaceOrInsertSection(
  source: string,
  startMarker: string,
  endMarker: string,
  newContent: string
): SourceEdit {
  const startIdx = source.indexOf(startMarker);
  const endIdx = source.indexOf(endMarker);

  // If both markers exist, replace content between them
  if (startIdx !== -1 && endIdx !== -1) {
    const before = source.slice(0, startIdx + startMarker.length);
    const after = source.slice(endIdx);
    const newCode = before + '\n' + newContent + '\n' + after;

    // Check if content actually changed
    const originalContent = source.slice(startIdx + startMarker.length, endIdx);
    const changed = originalContent.trim() !== newContent.trim();

    return { code: newCode, changed };
  }

  // Markers don't exist - insert them after imports (if any)
  const insertIdx = findInsertPositionAfterImports(source);
  const before = source.slice(0, insertIdx);
  const after = source.slice(insertIdx);

  const newSection = ['', startMarker, newContent, endMarker, ''].join('\n');

  return {
    code: before + newSection + after,
    changed: true,
  };
}

/**
 * Find the position after all imports in the source code
 */
function findInsertPositionAfterImports(source: string): number {
  const sourceFile = parseSource(source);

  let lastImportEnd = 0;

  ts.forEachChild(sourceFile, (node) => {
    if (ts.isImportDeclaration(node)) {
      lastImportEnd = node.end;
    }
  });

  // Find the next line after the last import
  if (lastImportEnd > 0) {
    const nextNewline = source.indexOf('\n', lastImportEnd);
    return nextNewline !== -1 ? nextNewline + 1 : lastImportEnd;
  }

  // No imports - insert at the very beginning
  return 0;
}
