/**
 * Tests for compile command
 * Uses direct function calls for speed, with CLI smoke tests for wiring
 */

import { parser } from '../../src/parser/annotation-parser';
import { generateCode } from '../../src/api/generate';
import { generateInPlace } from '../../src/api/generate-in-place';
import { captureConsole } from '../helpers/console-capture';

// Present in a file once compile has written the generated body into it.
const GENERATED_MARKER = 'DO NOT EDIT - This section is auto-generated by Flow Weaver';

describe('code generation (pure functions)', () => {
  describe('generateCode', () => {
    it('should generate valid code for simple workflow', () => {
      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function simpleWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const result = parser.parseFromString(content, 'simple.ts');
      expect(result.errors).toHaveLength(0);

      const generated = generateCode(result.workflows[0], {
        production: false,
      });
      expect(generated).toContain('GeneratedExecutionContext');
      expect(generated).toContain('simpleWorkflow');
    });

    it('should generate production code without debug types', () => {
      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function prodWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const result = parser.parseFromString(content, 'prod.ts');
      const generated = generateCode(result.workflows[0], { production: true });

      expect(generated).not.toContain('TDebugger');
    });

    it('should handle multiple nodes', () => {
      const content = `
/**
 * @flowWeaver nodeType
 */
function nodeA(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver nodeType
 */
function nodeB(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node a nodeA
 * @node b nodeB
 * @connect a.onSuccess -> b.execute
 * @connect b.onSuccess -> Exit.onSuccess
 */
export function multiNodeWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const result = parser.parseFromString(content, 'multi.ts');
      const generated = generateCode(result.workflows[0], {
        production: false,
      });

      expect(generated).toContain('nodeA');
      expect(generated).toContain('nodeB');
    });
  });

  describe('compileCommand dry-run', () => {
    it('--dry-run prevents file modification', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      // Create temp file with workflow content
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-dryrun-'));
      const tmpFile = path.join(tmpDir, 'dry-run-test.ts');
      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function dryRunWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      fs.writeFileSync(tmpFile, content);
      const originalContent = fs.readFileSync(tmpFile, 'utf8');

      try {
        await compileCommand(tmpFile, { dryRun: true });
        const afterContent = fs.readFileSync(tmpFile, 'utf8');
        // File should be unchanged
        expect(afterContent).toBe(originalContent);
      } finally {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileWorkflow validation gate (#42)', () => {
    it('should reject compilation when workflow has validation errors (#42)', async () => {
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');
      const { compileWorkflow } = await import('../../src/api/compile');

      // Create a workflow that references a non-existent node type
      const content = `
/**
 * @flowWeaver nodeType
 */
function realNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node r realNode
 * @node g ghostNode
 * @connect r.onSuccess -> g.execute
 * @connect g.onSuccess -> Exit.onSuccess
 */
export function invalidWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-validate-'));
      const tmpFile = path.join(tmpDir, 'invalid-workflow.ts');
      fs.writeFileSync(tmpFile, content);

      try {
        await expect(compileWorkflow(tmpFile, { write: false })).rejects.toThrow(/[Vv]alidation error|[Pp]arse error/);
      } finally {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should allow compilation when workflow is valid (#42)', async () => {
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');
      const { compileWorkflow } = await import('../../src/api/compile');

      const content = `
/**
 * @flowWeaver nodeType
 */
function goodNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node g goodNode
 * @connect g.onSuccess -> Exit.onSuccess
 */
export function validWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-validate-'));
      const tmpFile = path.join(tmpDir, 'valid-workflow.ts');
      fs.writeFileSync(tmpFile, content);

      try {
        // Should not throw. A valid workflow passes the validation gate.
        const result = await compileWorkflow(tmpFile, { write: false });
        expect(result.code).toBeDefined();
        expect(result.code).toContain('GeneratedExecutionContext');
      } finally {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileCommand --verbose', () => {
    it('should show "Skipped" via logger.info when verbose is true on non-workflow file', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-verbose-'));
      const tmpFile = path.join(tmpDir, 'no-workflow.ts');
      fs.writeFileSync(tmpFile, 'export const foo = 42;\n');

      const output: string[] = [];
      const origLog = console.log;
      console.log = (...args: unknown[]) => {
        output.push(args.map(String).join(' '));
      };

      try {
        await compileCommand(tmpFile, { verbose: true });
        const joined = output.join('\n');
        expect(joined).toContain('skip');
      } finally {
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should skip files without @flowWeaver before parsing (no import error)', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-skip-'));
      const tmpFile = path.join(tmpDir, 'main.ts');
      // File imports a nonexistent module. It would cause a parse error if not skipped.
      fs.writeFileSync(tmpFile, 'import { foo } from "./nonexistent-module.js";\nexport const bar = foo;\n');

      const errorOutput: string[] = [];
      const origError = console.error;
      const origLog = console.log;
      console.error = (...args: unknown[]) => {
        errorOutput.push(args.map(String).join(' '));
      };
      console.log = () => {}; // suppress normal output

      try {
        await compileCommand(tmpFile, { verbose: true });
        const joined = errorOutput.join('\n');
        // Should NOT contain import error or any error
        expect(joined).not.toContain('Import error');
        expect(joined).not.toContain('Failed to compile');
      } finally {
        console.error = origError;
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('--clean flag (skipParamReturns)', () => {
    const workflowWithPorts = `
/**
 * @flowWeaver nodeType @expression
 */
function greet(name: string): { greeting: string } {
  return { greeting: \`Hello, \${name}!\` };
}

/**
 * @flowWeaver workflow
 * @node g greet
 * @connect Start.name -> g.name
 * @connect g.greeting -> Exit.message
 */
export function cleanTestWorkflow(
  execute: boolean,
  params: { name: string }
): { onSuccess: boolean; onFailure: boolean; message: string } {
  throw new Error("Compile with: fw compile <file>");
}
`;

    it('compile --clean should omit @param/@returns from output', () => {
      const result = parser.parseFromString(workflowWithPorts, 'clean-test.ts');
      expect(result.errors).toHaveLength(0);

      const generated = generateInPlace(workflowWithPorts, result.workflows[0], {
        skipParamReturns: true,
      });

      expect(generated.hasChanges).toBe(true);
      // Should have the workflow annotation
      expect(generated.code).toContain('@flowWeaver workflow');
      // Should NOT have @param or @returns lines
      expect(generated.code).not.toMatch(/^\s*\*\s*@param\b/m);
      expect(generated.code).not.toMatch(/^\s*\*\s*@returns\b/m);
    });

    it('compile without --clean should emit @param/@returns as before', () => {
      const result = parser.parseFromString(workflowWithPorts, 'noclean-test.ts');
      expect(result.errors).toHaveLength(0);

      const generated = generateInPlace(workflowWithPorts, result.workflows[0], {});

      expect(generated.hasChanges).toBe(true);
      expect(generated.code).toContain('@flowWeaver workflow');
      // Should have @param and @returns lines
      expect(generated.code).toMatch(/^\s*\*\s*@param\b/m);
      expect(generated.code).toMatch(/^\s*\*\s*@returns\b/m);
    });

    it('--clean should preserve all other annotations (@node, @connect, @position)', () => {
      const result = parser.parseFromString(workflowWithPorts, 'clean-preserve.ts');
      expect(result.errors).toHaveLength(0);

      const generated = generateInPlace(workflowWithPorts, result.workflows[0], {
        skipParamReturns: true,
      });

      expect(generated.code).toContain('@node');
      expect(generated.code).toContain('@connect');
    });

    it('compileCommand should pass clean option to generateInPlace', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-clean-'));
      const tmpFile = path.join(tmpDir, 'clean-cmd-test.ts');
      fs.writeFileSync(tmpFile, workflowWithPorts);

      const origLog = console.log;
      console.log = () => {};

      try {
        await compileCommand(tmpFile, { clean: true });
        const compiled = fs.readFileSync(tmpFile, 'utf8');
        expect(compiled).toContain('@flowWeaver workflow');
        expect(compiled).not.toMatch(/^\s*\*\s*@param\b/m);
        expect(compiled).not.toMatch(/^\s*\*\s*@returns\b/m);
      } finally {
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileCommand --strict validation', () => {
    // A string output wired into a number input: a lossy coercion, which is a
    // warning by default and an error under --strict.
    const coercionWorkflow = `
/**
 * @flowWeaver nodeType
 * @input value
 * @output out
 */
function nodeA(execute: boolean, value: string): { onSuccess: boolean; onFailure: boolean; out: string } {
  return { onSuccess: true, onFailure: false, out: value };
}

/**
 * @flowWeaver nodeType
 * @input data
 * @output result
 */
function nodeB(execute: boolean, data: number): { onSuccess: boolean; onFailure: boolean; result: number } {
  return { onSuccess: true, onFailure: false, result: data };
}

/**
 * @flowWeaver workflow
 * @node a nodeA
 * @node b nodeB
 * @connect Start.execute -> a.execute
 * @connect Start.value -> a.value
 * @connect a.onSuccess -> b.execute
 * @connect a.out -> b.data
 * @connect b.onSuccess -> Exit.onSuccess
 * @connect b.result -> Exit.result
 */
export function strictWorkflow(execute: boolean, params: { value: string }): Promise<{ onSuccess: boolean; onFailure: boolean; result: number }> {
  throw new Error("Not implemented");
}
`;

    it('should compile with a coercion warning when not strict', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-strict-'));
      const tmpFile = path.join(tmpDir, 'strict-test.ts');
      fs.writeFileSync(tmpFile, coercionWorkflow);
      const out = captureConsole();

      try {
        await compileCommand(tmpFile, { strict: false });
        expect(fs.readFileSync(tmpFile, 'utf8')).toContain(GENERATED_MARKER);
        expect(out.of('warn')).toContain('Lossy Type Conversion');
      } finally {
        out.restore();
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should reject compilation in strict mode when workflow has a coercion warning', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-strict-'));
      const tmpFile = path.join(tmpDir, 'strict-test.ts');
      fs.writeFileSync(tmpFile, coercionWorkflow);
      const out = captureConsole();

      try {
        await expect(compileCommand(tmpFile, { strict: true })).rejects.toThrow('1 file(s) failed to compile');
        expect(out.of('error')).toContain('Type Incompatible');
        // A refused file is left as written.
        expect(fs.readFileSync(tmpFile, 'utf8')).toBe(coercionWorkflow);
      } finally {
        out.restore();
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileCommand --source-map', () => {
    it('should generate .map file when sourceMap is true', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function mapWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-srcmap-'));
      const tmpFile = path.join(tmpDir, 'srcmap-test.ts');
      fs.writeFileSync(tmpFile, content);

      const origLog = console.log;
      console.log = () => {};

      try {
        await compileCommand(tmpFile, { sourceMap: true });
        const mapPath = tmpFile + '.map';
        expect(fs.existsSync(mapPath)).toBe(true);
        const compiled = fs.readFileSync(tmpFile, 'utf8');
        expect(compiled).toContain('sourceMappingURL');
      } finally {
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileCommand --format', () => {
    it('should accept esm format option', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function formatWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-format-'));
      const tmpFile = path.join(tmpDir, 'format-test.ts');
      fs.writeFileSync(tmpFile, content);

      const origLog = console.log;
      console.log = () => {};

      const out = captureConsole();

      try {
        await compileCommand(tmpFile, { format: 'esm' });
        expect(fs.readFileSync(tmpFile, 'utf8')).toContain(GENERATED_MARKER);
        expect(out.of('log')).toContain('1 file compiled (ESM)');
      } finally {
        out.restore();
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should accept cjs format option', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function cjsWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-cjs-'));
      const tmpFile = path.join(tmpDir, 'cjs-test.ts');
      fs.writeFileSync(tmpFile, content);

      const origLog = console.log;
      console.log = () => {};

      const out = captureConsole();

      try {
        await compileCommand(tmpFile, { format: 'cjs' });
        expect(fs.readFileSync(tmpFile, 'utf8')).toContain(GENERATED_MARKER);
        expect(out.of('log')).toContain('1 file compiled (CJS)');
      } finally {
        out.restore();
        console.log = origLog;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('compileCommand glob expansion', () => {
    it('should expand directory input to glob pattern', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function dirWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-glob-'));
      fs.writeFileSync(path.join(tmpDir, 'workflow.ts'), content);
      fs.mkdirSync(path.join(tmpDir, 'nested'));
      fs.writeFileSync(path.join(tmpDir, 'nested', 'other.ts'), content.replace('dirWorkflow', 'otherWorkflow'));
      const out = captureConsole();

      try {
        // Passing a directory should auto-expand to **/*.ts, nested ones included
        await compileCommand(tmpDir, {});
        expect(fs.readFileSync(path.join(tmpDir, 'workflow.ts'), 'utf8')).toContain(GENERATED_MARKER);
        expect(fs.readFileSync(path.join(tmpDir, 'nested', 'other.ts'), 'utf8')).toContain(GENERATED_MARKER);
        expect(out.of('log')).toMatch(/2 files compiled/);
      } finally {
        out.restore();
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should throw when no files match', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');

      await expect(compileCommand('/nonexistent/path/that/does/not/exist/**/*.ts', {})).rejects.toThrow(
        /No files found|Compilation failed/,
      );
    });
  });

  // Inngest compile target tests are in flow-weaver-pack-inngest

  describe('compileCommand error paths', () => {
    it('should report errors and throw with error count for a workflow with an unknown node type', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      // nonExistentType is never declared with @flowWeaver nodeType. fw validate
      // rejects this, so compile must refuse it too rather than generate code.
      const content = `
/**
 * @flowWeaver workflow
 * @node ghost nonExistentType
 * @connect ghost.onSuccess -> Exit.onSuccess
 */
export function badWorkflow(execute: boolean): Promise<{ onSuccess: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-parse-err-'));
      const tmpFile = path.join(tmpDir, 'bad.ts');
      fs.writeFileSync(tmpFile, content);
      const out = captureConsole();

      try {
        await expect(compileCommand(tmpFile, {})).rejects.toThrow('1 file(s) failed to compile');
        expect(out.of('error')).toContain("Node type 'nonExistentType' doesn't exist");
        expect(out.of('log')).toContain('0 compiled, 1 failed');
        expect(fs.readFileSync(tmpFile, 'utf8')).toBe(content);
      } finally {
        out.restore();
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });

    it('should throw on strict mode with validation errors', async () => {
      const { compileCommand } = await import('../../src/cli/commands/compile');
      const fs = await import('fs');
      const os = await import('os');
      const path = await import('path');

      // A workflow with a known validation issue: connecting to nonexistent port
      // causes a validation error that --strict catches
      const content = `
/**
 * @flowWeaver nodeType
 */
function goodNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node g goodNode
 * @node h goodNode
 * @connect g.onSuccess -> h.execute
 * @connect h.onSuccess -> Exit.onSuccess
 * @connect g.nonexistentPort -> h.nonexistentPort
 */
export function strictErrorWf(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fw-strict-err-'));
      const tmpFile = path.join(tmpDir, 'strict-error.ts');
      fs.writeFileSync(tmpFile, content);

      const origLog = console.log;
      const origError = console.error;
      console.log = () => {};
      console.error = () => {};

      try {
        // With strict mode, validation errors cause a throw
        await expect(compileCommand(tmpFile, { strict: true })).rejects.toThrow(/failed/i);
      } finally {
        console.log = origLog;
        console.error = origError;
        fs.rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });

  describe('generateInPlace', () => {
    it('should be stable from the first compilation', () => {
      // The first compile injects the params and runtime parameters. The next
      // parse must read them back as no user params, so a second compile
      // changes nothing.
      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function stableWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const result = parser.parseFromString(content, 'stable.ts');

      // First compilation
      const first = generateInPlace(content, result.workflows[0], {
        production: false,
      });
      expect(first.hasChanges).toBe(true);

      // Second compilation
      const result2 = parser.parseFromString(first.code, 'stable2.ts');
      // The injected `params: Record<string, unknown> = {}` declares no ports.
      expect(Object.keys(result2.workflows[0].startPorts)).toEqual(['execute']);
      const second = generateInPlace(first.code, result2.workflows[0], {
        production: false,
      });
      expect(second.hasChanges).toBe(false);
      expect(second.code).toBe(first.code);

      // Third compilation - should stabilize
      const result3 = parser.parseFromString(second.code, 'stable3.ts');
      const third = generateInPlace(second.code, result3.workflows[0], {
        production: false,
      });

      // After stabilization, code should be identical
      expect(second.code).toBe(third.code);
      expect(third.hasChanges).toBe(false);
    });

    it('should generate code in place within source', () => {
      const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function inPlaceWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
      const result = parser.parseFromString(content, 'inplace.ts');
      const generated = generateInPlace(content, result.workflows[0], {
        production: false,
      });

      expect(generated.hasChanges).toBe(true);
      expect(generated.code).toContain('GeneratedExecutionContext');
      expect(generated.code).toContain('@flow-weaver-runtime-start');
    });

    it('injects a `params` parameter when the author signature omits it (zero-data-port workflow)', () => {
      // Regression: the generated body always references `params` (the
      // recursion-depth guard reads `params.__rd__`). A workflow whose
      // author signature declares NO data ports (only `execute`, e.g. a
      // single zero-input node) used to compile without `params`, so the body
      // threw `ReferenceError: params is not
      // defined` at runtime. The in-place generator must inject `params`.
      const content = `
/**
 * @flowWeaver nodeType
 * @expression
 * @output never - Never produced
 */
function boom(): { never: string } {
  throw new Error('always throws');
}

/**
 * @flowWeaver workflow
 * @node b boom
 * @connect b.never -> Exit.never
 */
export function alwaysThrows(execute: boolean): { onSuccess: boolean; onFailure: boolean; never: string } {
  throw new Error('Not implemented');
}
`;
      const result = parser.parseFromString(content, 'zero-params.ts');
      expect(result.errors).toHaveLength(0);
      const generated = generateInPlace(content, result.workflows[0], {
        production: false,
      });

      // The body references params (the recursion-depth guard reads it via
      // a TS cast). The signature must now declare it.
      expect(generated.code).toContain('params as { __rd__?: number }');
      expect(generated.code).toMatch(/function alwaysThrows\(\s*execute[^)]*\bparams\b/);
      // params must precede __runtime__ (positional order is part of the ABI).
      // runtime invokes fn(execute, params, ...)).
      const sig = generated.code.slice(
        generated.code.indexOf('function alwaysThrows('),
        generated.code.indexOf(')', generated.code.indexOf('function alwaysThrows(')) + 1,
      );
      expect(sig.indexOf('params')).toBeLessThan(sig.indexOf('__runtime__'));
    });

    it('does not duplicate `params` when the author already declares it', () => {
      const content = `
/**
 * @flowWeaver nodeType
 * @expression
 * @output result - Echoed value
 */
function echoNode(message: string): { result: string } {
  return { result: message };
}

/**
 * @flowWeaver workflow
 * @param {string} message - The message
 * @node e echoNode
 * @connect Start.message -> e.message
 * @connect e.result -> Exit.result
 */
export function echoFlow(execute: boolean, params: { message: string }): { onSuccess: boolean; onFailure: boolean; result: string } {
  throw new Error('Not implemented');
}
`;
      const result = parser.parseFromString(content, 'has-params.ts');
      const generated = generateInPlace(content, result.workflows[0], {
        production: false,
      });
      const sig = generated.code.slice(
        generated.code.indexOf('function echoFlow('),
        generated.code.indexOf(')', generated.code.indexOf('function echoFlow(')) + 1,
      );
      // Exactly one `params` in the signature (no duplicate injected).
      expect(sig.match(/\bparams\b/g)?.length).toBe(1);
    });
  });
});
