/**
 * Tests for CLI watch command
 * Note: Watch command runs indefinitely, so these tests use timeouts and child processes
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { spawn, ChildProcess } from 'child_process';

const TEMP_DIR = path.join(os.tmpdir(), `flow-weaver-watch-${process.pid}`);
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const CLI_ENTRY = path.join(PROJECT_ROOT, 'src/cli/index.ts');
// The CLI runs in this child itself, loaded through tsx, not under npx: a
// signal sent to the child reaches the watcher, and the exit code is the CLI's.
// Under npx the watcher is a grandchild that can outlive npx and hold stdout.
const TSX = ['--import', 'tsx'];

// Build a clean env for spawned CLI processes: strip VITEST* vars so the
// CLI entry guard doesn't skip program.parse().
const cliEnv = Object.fromEntries(
  Object.entries(process.env).filter(([k]) => !k.startsWith('VITEST')),
);

// Setup and cleanup
beforeAll(() => {
  fs.mkdirSync(TEMP_DIR, { recursive: true });
});

afterEach(() => {
  if (fs.existsSync(TEMP_DIR)) {
    const files = fs.readdirSync(TEMP_DIR);
    for (const file of files) {
      const filePath = path.join(TEMP_DIR, file);
      const stat = fs.statSync(filePath);
      if (stat.isDirectory()) {
        fs.rmSync(filePath, { recursive: true, force: true });
      } else {
        fs.unlinkSync(filePath);
      }
    }
  }
});

afterAll(() => {
  fs.rmSync(TEMP_DIR, { recursive: true, force: true });
});

describe('WatchOptions type', () => {
  it('WatchOptions accepts onRecompile callback', async () => {
    // Import the type and verify the interface accepts onRecompile
    const mod = await import('../../src/cli/commands/watch');

    // WatchOptions should be an interface extending CompileOptions with onRecompile
    // We test this by verifying the module exports are correct and the type compiles
    expect(mod.watchCommand).toBeInstanceOf(Function);

    // Create a valid WatchOptions-shaped object
    const options: import('../../src/cli/commands/watch').WatchOptions = {
      onRecompile: (_filePath: string, _success: boolean, _errors?: string[]) => {
        // callback should be accepted
      },
    };
    expect(options.onRecompile).toBeInstanceOf(Function);
  });
});

describe('CLI watch command', () => {
  let watchProcess: ChildProcess | null = null;

  afterEach(() => {
    // Clean up any running watch process
    if (watchProcess && !watchProcess.killed) {
      watchProcess.kill('SIGTERM');
      watchProcess = null;
    }
  });

  it('should start watch mode and perform initial compilation', async () => {
    const testFile = path.join(TEMP_DIR, 'watch-test.ts');
    const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function watchTestWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
    fs.writeFileSync(testFile, content);

    const output = await new Promise<string>((resolve, reject) => {
      const timeout = setTimeout(() => {
        if (!child.killed) {
          child.kill('SIGTERM');
        }
        reject(new Error('Test timed out waiting for watch mode output'));
      }, 90000);

      const child = spawn(process.execPath, [...TSX, CLI_ENTRY, 'watch', testFile], {
        cwd: PROJECT_ROOT,
        env: cliEnv,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      // Each test acts on its own child: a late event from an earlier test's
      // process must not reach the next test's through the shared variable.
      watchProcess = child;

      let output = '';

      child.stdout?.on('data', (data) => {
        output += data.toString();
        // Check for successful initial compilation
        if (output.includes('Watching for file changes')) {
          clearTimeout(timeout);
          if (!child.killed) {
            child.kill('SIGTERM');
          }
          resolve(output);
        }
      });

      child.stderr?.on('data', (data) => {
        output += data.toString();
      });

      child.on('error', (err) => {
        clearTimeout(timeout);
        reject(err);
      });
    });

    expect(output).toContain('Initial compilation...');
    expect(output).toContain('1 file compiled');
    expect(output).not.toContain('Initial compilation failed');
    // The initial compile wrote the generated body into the file.
    expect(fs.readFileSync(testFile, 'utf8')).toContain('DO NOT EDIT - This section is auto-generated by Flow Weaver');
  }, 120000);

  it('should terminate when killed', async () => {
    const testFile = path.join(TEMP_DIR, 'sigint-test.ts');
    const content = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function sigintWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
    fs.writeFileSync(testFile, content);

    let watchStarted = false;
    let output = '';
    const exit = await new Promise<{ code: number | null; signal: NodeJS.Signals | null }>((resolve, reject) => {
      const timeout = setTimeout(() => {
        if (!child.killed) {
          child.kill('SIGKILL');
        }
        reject(new Error('Test timed out'));
      }, 90000);

      const child = spawn(process.execPath, [...TSX, CLI_ENTRY, 'watch', testFile], {
        cwd: PROJECT_ROOT,
        env: cliEnv,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      // Each test acts on its own child: a late event from an earlier test's
      // process must not reach the next test's through the shared variable.
      watchProcess = child;

      child.stdout?.on('data', (data) => {
        output += data.toString();
        if (output.includes('Watching for file changes') && !watchStarted) {
          watchStarted = true;
          // Kill process after watch mode starts
          setTimeout(() => {
            if (!child.killed) {
              child.kill('SIGTERM');
            }
          }, 500);
        }
      });

      // 'close', not 'exit': it fires once stdout is drained, so the last
      // lines the process printed are in the output.
      child.on('close', (code, signal) => {
        clearTimeout(timeout);
        resolve({ code, signal });
      });

      child.on('error', (err) => {
        clearTimeout(timeout);
        reject(err);
      });
    });

    // It was watching, and SIGTERM ran its cleanup rather than the timeout's
    // SIGKILL ending it.
    expect(watchStarted).toBe(true);
    expect(exit.signal).not.toBe('SIGKILL');
    expect(output).toContain('Stopping watch mode...');
  }, 120000);

  it('should fail for non-existent file', async () => {
    let output = '';
    const code = await new Promise<number | null>((resolve, reject) => {
      const timeout = setTimeout(() => {
        if (!child.killed) {
          child.kill('SIGTERM');
        }
        reject(new Error('Test timed out'));
      }, 90000);

      const child = spawn(process.execPath, [...TSX, CLI_ENTRY, 'watch', '/nonexistent/file.ts'], {
        cwd: PROJECT_ROOT,
        env: cliEnv,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      // Each test acts on its own child: a late event from an earlier test's
      // process must not reach the next test's through the shared variable.
      watchProcess = child;
      child.stdout?.on('data', (data) => {
        output += data.toString();
      });
      child.stderr?.on('data', (data) => {
        output += data.toString();
      });

      // Resolve rather than asserting here: an expect() that throws inside this
      // async callback escapes the Promise as an uncaught exception, which
      // fails the whole vitest run (not just this test).
      child.on('close', (exitCode) => {
        clearTimeout(timeout);
        resolve(exitCode);
      });

      child.on('error', (err) => {
        clearTimeout(timeout);
        reject(err);
      });
    });

    // A null code would mean the process was signalled (e.g. SIGTERM'd on a
    // slow box) rather than exiting on its own.
    expect(code).toBe(1);
    expect(output).toContain('No files match /nonexistent/file.ts; nothing to watch');
    // It never claims to be watching a file that is not there.
    expect(output).not.toContain('Watching for file changes');
  }, 120000);
});
