/**
 * DO NOT EDIT - generated by scripts/generate-built-in-registry.ts
 *
 * Registry of built-in node types for auto-injection into the parser.
 * Generated from the actual source files in src/built-in-nodes/.
 */

import type { TNodeTypeAST } from '../ast/types';

export const BUILT_IN_NODE_TYPES: TNodeTypeAST[] = [
  {
    type: 'NodeType',
    name: 'delay',
    functionName: 'delay',
    isAsync: true,
    hasSuccessPort: true,
    hasFailurePort: true,
    executeWhen: 'CONJUNCTION',
    variant: 'FUNCTION',
    inputs: {
      execute: { dataType: 'STEP', label: 'Execute' },
      duration: { dataType: 'STRING', label: 'Duration to sleep (e.g. "30s", "5m", "1h", "2d")', tsType: 'string' },
    },
    outputs: {
      onSuccess: { dataType: 'STEP', label: 'On Success', isControlFlow: true },
      onFailure: { dataType: 'STEP', label: 'On Failure', isControlFlow: true, failure: true },
      elapsed: { dataType: 'BOOLEAN', label: 'Always true after sleep completes', tsType: 'boolean' },
    },
    helperText: `
function __fw_getMockConfig() {
    return globalThis.__fw_mocks__;
}

function __fw_lookupMock(section, key) {
    if (!section)
        return undefined;
    const nodeId = globalThis.__fw_current_node_id__;
    if (nodeId) {
        const qualified = section[\`\${nodeId}:\${key}\`];
        if (qualified !== undefined)
            return qualified;
    }
    return section[key];
}
`.trim(),
    helperTextProduction: undefined,
    functionText: `
async function delay(execute, duration) {
    if (!execute)
        return { onSuccess: false, onFailure: false, elapsed: false };
    const mocks = __fw_getMockConfig();
    if (mocks?.fast) {
        await new Promise((resolve) => setTimeout(resolve, 1));
    }
    else {
        const ms = __fw_parseDuration(duration);
        await new Promise((resolve) => setTimeout(resolve, ms));
    }
    return { onSuccess: true, onFailure: false, elapsed: true };
}
function __fw_parseDuration(duration) {
    const match = duration.match(/^(\\d+)(ms|s|m|h|d)$/);
    if (!match)
        return 0;
    const [, value, unit] = match;
    const multipliers = { ms: 1, s: 1000, m: 60000, h: 3600000, d: 86400000 };
    return parseInt(value) * (multipliers[unit] || 0);
}
`.trim(),
    functionTextProduction: `
async function delay(execute, duration) {
    if (!execute)
        return { onSuccess: false, onFailure: false, elapsed: false };
    const ms = __fw_parseDuration(duration);
    await new Promise((resolve) => setTimeout(resolve, ms));
    return { onSuccess: true, onFailure: false, elapsed: true };
}
function __fw_parseDuration(duration) {
    const match = duration.match(/^(\\d+)(ms|s|m|h|d)$/);
    if (!match)
        return 0;
    const [, value, unit] = match;
    const multipliers = { ms: 1, s: 1000, m: 60000, h: 3600000, d: 86400000 };
    return parseInt(value) * (multipliers[unit] || 0);
}
`.trim(),
  },
  {
    type: 'NodeType',
    name: 'waitForEvent',
    functionName: 'waitForEvent',
    isAsync: true,
    hasSuccessPort: true,
    hasFailurePort: true,
    executeWhen: 'CONJUNCTION',
    variant: 'FUNCTION',
    inputs: {
      execute: { dataType: 'STEP', label: 'Execute' },
      eventName: { dataType: 'STRING', label: 'Event name to wait for (e.g. "app/approval.received")', tsType: 'string' },
      match: { dataType: 'STRING', label: 'Field to match between trigger and waited event (e.g. "data.requestId")', tsType: 'string', optional: true },
      timeout: { dataType: 'STRING', label: 'Max wait time (e.g. "24h", "7d"). Empty = no timeout', tsType: 'string', optional: true },
    },
    outputs: {
      onSuccess: { dataType: 'STEP', label: 'On Success', isControlFlow: true },
      onFailure: { dataType: 'STEP', label: 'On Failure', isControlFlow: true, failure: true },
      eventData: { dataType: 'OBJECT', label: 'The received event\'s data payload', tsType: 'object' },
    },
    helperText: `
function __fw_getMockConfig() {
    return globalThis.__fw_mocks__;
}

function __fw_lookupMock(section, key) {
    if (!section)
        return undefined;
    const nodeId = globalThis.__fw_current_node_id__;
    if (nodeId) {
        const qualified = section[\`\${nodeId}:\${key}\`];
        if (qualified !== undefined)
            return qualified;
    }
    return section[key];
}
`.trim(),
    helperTextProduction: undefined,
    functionText: `
async function waitForEvent(execute, eventName, match, timeout) {
    if (!execute)
        return { onSuccess: false, onFailure: false, eventData: {} };
    const mocks = __fw_getMockConfig();
    if (mocks) {
        const mockData = __fw_lookupMock(mocks.events, eventName);
        if (mockData !== undefined) {
            return { onSuccess: true, onFailure: false, eventData: mockData };
        }
        return { onSuccess: false, onFailure: true, eventData: {} };
    }
    return { onSuccess: true, onFailure: false, eventData: {} };
}
`.trim(),
    functionTextProduction: `
async function waitForEvent(execute, eventName, match, timeout) {
    if (!execute)
        return { onSuccess: false, onFailure: false, eventData: {} };
    return { onSuccess: true, onFailure: false, eventData: {} };
}
`.trim(),
  },
  {
    type: 'NodeType',
    name: 'invokeWorkflow',
    functionName: 'invokeWorkflow',
    isAsync: true,
    hasSuccessPort: true,
    hasFailurePort: true,
    executeWhen: 'CONJUNCTION',
    variant: 'FUNCTION',
    inputs: {
      execute: { dataType: 'STEP', label: 'Execute' },
      functionId: { dataType: 'STRING', label: 'Function ID of the workflow to invoke (e.g. "my-service/sub-workflow")', tsType: 'string' },
      payload: { dataType: 'OBJECT', label: 'Data to pass as event.data to the invoked function', tsType: 'object' },
      timeout: { dataType: 'STRING', label: 'Max wait time (e.g. "1h")', tsType: 'string', optional: true },
    },
    outputs: {
      onSuccess: { dataType: 'STEP', label: 'On Success', isControlFlow: true },
      onFailure: { dataType: 'STEP', label: 'On Failure', isControlFlow: true, failure: true },
      result: { dataType: 'OBJECT', label: 'Return value from the invoked function', tsType: 'object' },
    },
    helperText: `
function __fw_getMockConfig() {
    return globalThis.__fw_mocks__;
}

function __fw_lookupMock(section, key) {
    if (!section)
        return undefined;
    const nodeId = globalThis.__fw_current_node_id__;
    if (nodeId) {
        const qualified = section[\`\${nodeId}:\${key}\`];
        if (qualified !== undefined)
            return qualified;
    }
    return section[key];
}
`.trim(),
    helperTextProduction: undefined,
    functionText: `
async function invokeWorkflow(execute, functionId, payload, timeout) {
    if (!execute)
        return { onSuccess: false, onFailure: false, result: {} };
    const mocks = __fw_getMockConfig();
    if (mocks) {
        const mockResult = __fw_lookupMock(mocks.invocations, functionId);
        if (mockResult !== undefined) {
            return { onSuccess: true, onFailure: false, result: mockResult };
        }
        return { onSuccess: false, onFailure: true, result: {} };
    }
    const registry = globalThis.__fw_workflow_registry__;
    if (registry?.[functionId]) {
        try {
            const result = await registry[functionId](true, payload);
            return { onSuccess: true, onFailure: false, result: result ?? {} };
        }
        catch {
            return { onSuccess: false, onFailure: true, result: {} };
        }
    }
    return { onSuccess: true, onFailure: false, result: {} };
}
`.trim(),
    functionTextProduction: `
async function invokeWorkflow(execute, functionId, payload, timeout) {
    if (!execute)
        return { onSuccess: false, onFailure: false, result: {} };
    const registry = globalThis.__fw_workflow_registry__;
    if (registry?.[functionId]) {
        try {
            const result = await registry[functionId](true, payload);
            return { onSuccess: true, onFailure: false, result: result ?? {} };
        }
        catch {
            return { onSuccess: false, onFailure: true, result: {} };
        }
    }
    return { onSuccess: true, onFailure: false, result: {} };
}
`.trim(),
  },
  {
    type: 'NodeType',
    name: 'waitForAgent',
    functionName: 'waitForAgent',
    isAsync: true,
    hasSuccessPort: true,
    hasFailurePort: true,
    executeWhen: 'CONJUNCTION',
    variant: 'FUNCTION',
    inputs: {
      execute: { dataType: 'STEP', label: 'Execute' },
      agentId: { dataType: 'STRING', label: 'Agent/task identifier', tsType: 'string' },
      context: { dataType: 'OBJECT', label: 'Context data to send to the agent', tsType: 'object' },
      prompt: { dataType: 'STRING', label: 'Message to display when requesting input', tsType: 'string', optional: true },
    },
    outputs: {
      onSuccess: { dataType: 'STEP', label: 'On Success', isControlFlow: true },
      onFailure: { dataType: 'STEP', label: 'On Failure', isControlFlow: true, failure: true },
      agentResult: { dataType: 'OBJECT', label: 'Result returned by the agent', tsType: 'object' },
    },
    helperText: `
function __fw_getMockConfig() {
    return globalThis.__fw_mocks__;
}

function __fw_lookupMock(section, key) {
    if (!section)
        return undefined;
    const nodeId = globalThis.__fw_current_node_id__;
    if (nodeId) {
        const qualified = section[\`\${nodeId}:\${key}\`];
        if (qualified !== undefined)
            return qualified;
    }
    return section[key];
}
`.trim(),
    helperTextProduction: undefined,
    functionText: `
async function waitForAgent(execute, agentId, context, prompt) {
    if (!execute)
        return { onSuccess: false, onFailure: false, agentResult: {} };
    const mocks = __fw_getMockConfig();
    const mockResult = __fw_lookupMock(mocks?.agents, agentId);
    if (mockResult !== undefined) {
        return { onSuccess: true, onFailure: false, agentResult: mockResult };
    }
    if (mocks?.agents) {
        return { onSuccess: false, onFailure: true, agentResult: {} };
    }
    const channel = globalThis.__fw_agent_channel__;
    if (channel) {
        const result = await channel.request({ agentId, context, prompt });
        return { onSuccess: true, onFailure: false, agentResult: result };
    }
    return { onSuccess: true, onFailure: false, agentResult: {} };
}
`.trim(),
    functionTextProduction: `
async function waitForAgent(execute, agentId, context, prompt) {
    if (!execute)
        return { onSuccess: false, onFailure: false, agentResult: {} };
    const channel = globalThis.__fw_agent_channel__;
    if (channel) {
        const result = await channel.request({ agentId, context, prompt });
        return { onSuccess: true, onFailure: false, agentResult: result };
    }
    return { onSuccess: true, onFailure: false, agentResult: {} };
}
`.trim(),
  },
];
