name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Compiler
        - CLI
        - Parser
        - Validator
        - MCP Server
        - Studio
        - VSCode Extension
        - Deployment
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      placeholder: Describe the problem you're trying to solve or the use case this would enable.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: How do you think this should work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds or alternative approaches you've considered?
