/**
 * Cross-file workflow: imports node types from separate files.
 * Tests compiler codegen type-safety bugs.
 */

import { parseConfig } from './nodes.js';
import { runTask } from './nodes.js';

// @flow-weaver-runtime-start
// ============================================================================
// DO NOT EDIT - This section is auto-generated by Flow Weaver
// ============================================================================

// ============================================================================
// Runtime Types
// ============================================================================

type TStatusType =
  | "RUNNING"
  | "SCHEDULED"
  | "SUCCEEDED"
  | "FAILED"
  | "CANCELLED"
  | "PENDING";

type TVariableIdentification = {
  nodeTypeName: string;
  id: string;
  scope?: string | undefined;
  side?: "start" | "exit" | undefined;
  portName: string;
  executionIndex: number;
  key?: string | undefined;
};

type TStatusChangedEvent = {
  type: "STATUS_CHANGED";
  nodeTypeName: string;
  id: string;
  scope?: string;
  side?: "start" | "exit";
  executionIndex: number;
  status: TStatusType;
  innerFlowInvocation?: boolean;
};

type TVariableSetEvent = {
  type: "VARIABLE_SET";
  identifier: TVariableIdentification;
  value?: unknown;
  innerFlowInvocation?: boolean;
};

type TErrorLogEvent = {
  type: "LOG_ERROR";
  nodeTypeName: string;
  id: string;
  scope?: string;
  side?: "start" | "exit";
  executionIndex: number;
  error: string;
  innerFlowInvocation?: boolean;
};

type TWorkflowCompletedEvent = {
  type: "WORKFLOW_COMPLETED";
  executionIndex: number;
  status: "SUCCEEDED" | "FAILED" | "CANCELLED";
  result?: unknown;
  innerFlowInvocation?: boolean;
};

type TEvent =
  | TStatusChangedEvent
  | TVariableSetEvent
  | TErrorLogEvent
  | TWorkflowCompletedEvent;

type TDebugger = {
  sendEvent: (event: TEvent) => void | Promise<void>;
  innerFlowInvocation: boolean;
  sessionId?: string;
};

declare const __flowWeaverDebugger__: TDebugger | undefined;

type TDebugController = {
  beforeNode(nodeId: string, ctx: GeneratedExecutionContext): Promise<boolean> | boolean;
  afterNode(nodeId: string, ctx: GeneratedExecutionContext): Promise<void> | void;
};

declare const __abortSignal__: AbortSignal | undefined;

interface VariableAddress {
  id: string;
  portName: string;
  executionIndex: number;
  nodeTypeName?: string | undefined;
  scope?: string | undefined;
  side?: 'start' | 'exit' | undefined;
}

interface ExecutionInfo {
  id: string;
  index: number;
  parentIndex?: number | undefined;
  scopeName?: string | undefined;
}

type VariableValue = unknown | (() => unknown) | (() => Promise<unknown>);

// ============================================================================
// Cancellation Error
// ============================================================================

class CancellationError extends Error {
  public readonly executionIndex: number;
  public readonly nodeId?: string;
  public readonly timestamp: number;

  constructor(
    message: string = 'Workflow execution cancelled',
    executionIndex: number = 0,
    nodeId?: string,
    timestamp: number = Date.now()
  ) {
    super(message);
    this.name = 'CancellationError';
    this.executionIndex = executionIndex;
    this.nodeId = nodeId;
    this.timestamp = timestamp;
  }

  static isCancellationError(error: unknown): error is CancellationError {
    return (
      error instanceof CancellationError ||
      (error instanceof Error && error.name === 'CancellationError')
    );
  }
}

// ============================================================================
// Execution Context
// ============================================================================

class GeneratedExecutionContext {
  private variables: Map<string, VariableValue> = new Map();
  private executions: Map<string, ExecutionInfo> = new Map();
  private executionCounter: number = 0;
  private nodeExecutionCounts: Map<string, number> = new Map();
  private isAsync: boolean;
  private flowWeaverDebugger?: TDebugger | undefined;
  private pullExecutors: Map<string, () => void | Promise<void>> = new Map();
  private nodeExecutionIndices: Map<string, number> = new Map();
  private abortSignal?: AbortSignal | undefined;

  constructor(isAsync: boolean = true, flowWeaverDebugger?: TDebugger, abortSignal?: AbortSignal) {
    this.isAsync = isAsync;
    this.flowWeaverDebugger = flowWeaverDebugger;
    this.abortSignal = abortSignal;
  }

  registerPullExecutor(id: string, executor: () => void | Promise<void>): void {
    this.pullExecutors.set(id, executor);
  }

  addExecution(id: string, parentIndex?: number, scopeName?: string): number {
    // Use per-node execution counter (each node starts at 0)
    const currentCount = this.nodeExecutionCounts.get(id) || 0;
    const index = currentCount;
    this.nodeExecutionCounts.set(id, currentCount + 1);
    this.executionCounter++;
    this.executions.set(this.getExecutionKey(id, index), {
      id,
      index,
      parentIndex,
      scopeName,
    });
    this.nodeExecutionIndices.set(id, index);
    return index;
  }

  setVariable(address: VariableAddress, value: VariableValue): void | Promise<void> {
    const key = this.getVariableKey(address);
    this.variables.set(key, value);
    if (this.flowWeaverDebugger) {
      const actualValue = typeof value === "function" ? value() : value;
      this.sendVariableSetEvent({
        identifier: {
          nodeTypeName: address.nodeTypeName || "unknown",
          id: address.id,
          portName: address.portName,
          executionIndex: address.executionIndex,
          key: "default",
          ...(address.scope && { scope: address.scope }),
          ...(address.side && { side: address.side }),
        },
        value: actualValue,
      });
    }
    return this.isAsync ? Promise.resolve() : undefined;
  }

  getVariable(address: VariableAddress): unknown | Promise<unknown> {
    const executor = this.pullExecutors.get(address.id);
    if (executor) {
      if (!this.hasVariable(address)) {
        const result = executor();
        // Handle async executor (returns Promise)
        if (result instanceof Promise) {
          return result.then(() => {
            const trackedIndex = this.nodeExecutionIndices.get(address.id);
            const finalAddress = trackedIndex !== undefined
              ? { ...address, executionIndex: trackedIndex }
              : address;
            return this.retrieveVariable(finalAddress);
          });
        }
        // Handle sync executor (returns void)
        const trackedIndex = this.nodeExecutionIndices.get(address.id);
        const finalAddress = trackedIndex !== undefined
          ? { ...address, executionIndex: trackedIndex }
          : address;
        return this.retrieveVariable(finalAddress);
      }
    }
    return this.retrieveVariable(address);
  }

  private retrieveVariable(address: VariableAddress): unknown | Promise<unknown> {
    const key = this.getVariableKey(address);
    if (!this.variables.has(key)) {
      throw new Error(`Variable not found: ${address.id}.${address.portName}[${address.executionIndex}]`);
    }
    const value = this.variables.get(key);
    if (typeof value === "function") {
      const result = value();
      if (result instanceof Promise) {
        return result;
      }
      return this.isAsync ? Promise.resolve(result) : result;
    }
    return this.isAsync ? Promise.resolve(value) : value;
  }

  hasVariable(address: VariableAddress): boolean {
    const key = this.getVariableKey(address);
    return this.variables.has(key);
  }

  getExecution(id: string, index: number): ExecutionInfo | undefined {
    return this.executions.get(this.getExecutionKey(id, index));
  }

  createScope(_parentNodeName: string, _parentIndex: number, _scopeName: string, cleanScope: boolean = false, isAsyncOverride?: boolean): GeneratedExecutionContext {
    const effectiveIsAsync = isAsyncOverride !== undefined ? isAsyncOverride : this.isAsync;
    const scopedContext = new GeneratedExecutionContext(effectiveIsAsync, this.flowWeaverDebugger, this.abortSignal);
    // For per-port function scopes (cleanScope=true), start with empty variables
    // For node-level scopes (cleanScope=false), inherit parent variables
    scopedContext.variables = cleanScope ? new Map() : new Map(this.variables);
    scopedContext.executions = new Map(this.executions);
    scopedContext.executionCounter = this.executionCounter;
    scopedContext.nodeExecutionCounts = new Map(this.nodeExecutionCounts);
    return scopedContext;
  }

  mergeScope(scopedContext: GeneratedExecutionContext): void {
    scopedContext.executions.forEach((info, key) => {
      this.executions.set(key, info);
    });
    scopedContext.variables.forEach((value, key) => {
      this.variables.set(key, value);
    });
    this.executionCounter = Math.max(this.executionCounter, scopedContext.executionCounter);
    scopedContext.nodeExecutionCounts.forEach((count, id) => {
      const currentCount = this.nodeExecutionCounts.get(id) || 0;
      this.nodeExecutionCounts.set(id, Math.max(currentCount, count));
    });
  }

  private getVariableKey(address: VariableAddress): string {
    return `${address.id}:${address.portName}:${address.executionIndex}`;
  }

  private getExecutionKey(id: string, index: number): string {
    return `${id}:${index}`;
  }

  getExecutionCount(): number {
    return this.executionCounter;
  }

  reset(): void {
    this.variables.clear();
    this.executions.clear();
    this.executionCounter = 0;
    this.nodeExecutionCounts.clear();
  }

  isAborted(): boolean {
    return this.abortSignal?.aborted ?? false;
  }

  checkAborted(nodeId?: string): void {
    if (this.abortSignal?.aborted) {
      throw new CancellationError(
        `Workflow execution cancelled${nodeId ? ` at ${nodeId}` : ''}`,
        this.executionCounter,
        nodeId
      );
    }
  }

  async sendStatusChangedEvent(args: {
    nodeTypeName: string;
    id: string;
    scope?: string;
    side?: "start" | "exit";
    executionIndex: number;
    status: TStatusType;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "STATUS_CHANGED",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  private async sendVariableSetEvent(args: {
    identifier: TVariableIdentification;
    value: unknown;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "VARIABLE_SET",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  async sendLogErrorEvent(args: {
    nodeTypeName: string;
    id: string;
    scope?: string;
    side?: "start" | "exit";
    executionIndex: number;
    error: string;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "LOG_ERROR",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  async sendWorkflowCompletedEvent(args: {
    executionIndex: number;
    status: "SUCCEEDED" | "FAILED" | "CANCELLED";
    result?: unknown;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "WORKFLOW_COMPLETED",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  serialize(): {
    variables: Record<string, unknown>;
    executions: Record<string, ExecutionInfo>;
    executionCounter: number;
    nodeExecutionCounts: Record<string, number>;
  } {
    const vars: Record<string, unknown> = {};
    for (const [key, value] of this.variables) {
      if (typeof value === "function") {
        try { vars[key] = (value as () => unknown)(); } catch { vars[key] = value; }
      } else {
        vars[key] = value;
      }
    }
    const execs: Record<string, ExecutionInfo> = {};
    for (const [key, info] of this.executions) { execs[key] = { ...info }; }
    const nodeCounts: Record<string, number> = {};
    for (const [key, count] of this.nodeExecutionIndices) { nodeCounts[key] = count; }
    return { variables: vars, executions: execs, executionCounter: this.executionCounter, nodeExecutionCounts: nodeCounts };
  }

  restore(data: {
    variables: Record<string, unknown>;
    executions: Record<string, ExecutionInfo>;
    executionCounter: number;
    nodeExecutionCounts: Record<string, number>;
  }): void {
    this.variables = new Map(Object.entries(data.variables));
    this.executions = new Map(Object.entries(data.executions));
    this.executionCounter = data.executionCounter;
    this.nodeExecutionIndices = new Map(Object.entries(data.nodeExecutionCounts));
  }
}

// @flow-weaver-runtime-end

/**
 * @flowWeaver workflow
 * @node parser parseConfig [position: 200 200]
 * @node runner runTask [position: 400 200]
 * @path Start -> parser -> runner -> Exit
 * @position Start 0 0
 * @position Exit 810 0
 * @connect runner.result -> Exit.output
 * @param execute [order:-1] - Execute
 * @param raw [order:0] - Raw config JSON
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns output [order:0] - Task output string
 */
export async function crossFileWorkflow(
  execute: boolean,
  params: { raw: string }, __abortSignal__?: AbortSignal,
): Promise<{ onSuccess: boolean; onFailure: boolean; output: string }> {
  // @flow-weaver-body-start
  // ============================================================================
  // DO NOT EDIT - This section is auto-generated by Flow Weaver
  // Edit the @flowWeaver annotations above to modify workflow behavior
  // ============================================================================

    const __effectiveDebugger__ = typeof __flowWeaverDebugger__ !== 'undefined' ? __flowWeaverDebugger__ : undefined;

    // Recursion depth protection
    const __rd__ = (params as { __rd__?: number }).__rd__ ?? 0;
    if (__rd__ >= 1000) {
      throw new Error('Max recursion depth exceeded (1000) in workflow "crossFileWorkflow"');
    }

    const ctx = new GeneratedExecutionContext(true, __effectiveDebugger__, __abortSignal__);

    // Debug controller for step-through debugging and checkpoint/resume
    const __ctrl__: TDebugController = (
      typeof globalThis !== 'undefined' && (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        ? (globalThis as unknown as { __fw_debug_controller__?: TDebugController }).__fw_debug_controller__
        : { beforeNode: () => true, afterNode: () => {} }
    )!;

    const startIdx = ctx.addExecution('Start');
    await ctx.setVariable({ id: 'Start', portName: 'execute', executionIndex: startIdx, nodeTypeName: 'Start' }, execute);
    await ctx.setVariable({ id: 'Start', portName: 'raw', executionIndex: startIdx, nodeTypeName: 'Start' }, params.raw);
    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Start',
      id: 'Start',
      executionIndex: startIdx,
      status: 'SUCCEEDED',
    });

    let parserIdx: number | undefined;
    let runnerIdx: number | undefined;

    let parser_success = false;

    if (await __ctrl__.beforeNode('parser', ctx)) {

      // ── parser (parseConfig) ──
      ctx.checkAborted('parser');
      parserIdx = ctx.addExecution('parser');
      if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'parser';
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'parseConfig',
        id: 'parser',
        executionIndex: parserIdx,
        status: 'RUNNING',
      });

      parser_success = false;

      try {
        await ctx.setVariable({ id: 'parser', portName: 'execute', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, true);
        const parser_raw = await ctx.getVariable({ id: 'Start', portName: 'raw', executionIndex: startIdx }) as string;
        await ctx.setVariable({ id: 'parser', portName: 'raw', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, parser_raw);
        const parserResult = parseConfig(parser_raw);
        const parserResult_raw: unknown = parserResult;
        await ctx.setVariable({ id: 'parser', portName: 'config', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, typeof parserResult_raw === 'object' && parserResult_raw !== null && 'config' in parserResult_raw ? parserResult_raw.config : parserResult_raw);
        await ctx.setVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, true);
        await ctx.setVariable({ id: 'parser', portName: 'onFailure', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'parseConfig',
          id: 'parser',
          executionIndex: parserIdx,
          status: 'SUCCEEDED',
        });
        await __ctrl__.afterNode('parser', ctx);
        parser_success = true;
      } catch (error: unknown) {
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'parseConfig',
          id: 'parser',
          executionIndex: parserIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'parseConfig',
            id: 'parser',
            executionIndex: parserIdx,
            error: error instanceof Error ? error.message : String(error),
          });
          await ctx.setVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, false);
          await ctx.setVariable({ id: 'parser', portName: 'onFailure', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, true);
          parser_success = false;
        }
        throw error;
      }
    } else {
      parserIdx = ctx.addExecution('parser');
      parser_success = true;
    }

    if (parser_success) {
      if (await __ctrl__.beforeNode('runner', ctx)) {

        // ── runner (runTask) ──
        ctx.checkAborted('runner');
        runnerIdx = ctx.addExecution('runner');
        if (typeof globalThis !== 'undefined') (globalThis as unknown as { __fw_current_node_id__?: string }).__fw_current_node_id__ = 'runner';
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'runTask',
          id: 'runner',
          executionIndex: runnerIdx,
          status: 'RUNNING',
        });

        try {
          const runner_execute = await ctx.getVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx! }) as boolean;
          await ctx.setVariable({ id: 'runner', portName: 'execute', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runner_execute);
          const runner_config = await ctx.getVariable({ id: 'parser', portName: 'config', executionIndex: parserIdx! }) as Parameters<typeof runTask>[1];
          await ctx.setVariable({ id: 'runner', portName: 'config', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runner_config);
          const runnerResult = runTask(runner_execute, runner_config);
          await ctx.setVariable({ id: 'runner', portName: 'result', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.result);
          await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.onSuccess);
          await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.onFailure);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'runTask',
            id: 'runner',
            executionIndex: runnerIdx,
            status: 'SUCCEEDED',
          });
          await __ctrl__.afterNode('runner', ctx);
        } catch (error: unknown) {
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'runTask',
            id: 'runner',
            executionIndex: runnerIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'runTask',
              id: 'runner',
              executionIndex: runnerIdx,
              error: error instanceof Error ? error.message : String(error),
            });
            await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
            await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, true);
          }
          throw error;
        }
      } else {
        runnerIdx = ctx.addExecution('runner');
      }

    } else {
      const runnerIdx = ctx.addExecution('runner');
      await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
      await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'runTask',
        id: 'runner',
        executionIndex: runnerIdx,
        status: 'CANCELLED',
      });
    }
    const exitIdx = ctx.addExecution('Exit');
    const exit_output = runnerIdx !== undefined ? await ctx.getVariable({ id: 'runner', portName: 'result', executionIndex: runnerIdx }) : undefined;
    await ctx.setVariable({ id: 'Exit', portName: 'output', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_output);
    const exit_onSuccess = runnerIdx !== undefined ? await ctx.getVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx }) : false;
    await ctx.setVariable({ id: 'Exit', portName: 'onSuccess', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_onSuccess);

    await ctx.setVariable({ id: 'Exit', portName: 'onFailure', executionIndex: exitIdx, nodeTypeName: 'Exit' }, false);
    const finalResult = { onFailure: false, output: exit_output as string, onSuccess: exit_onSuccess as boolean };

    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Exit',
      id: 'Exit',
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
    });
    ctx.sendWorkflowCompletedEvent({
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
      result: finalResult,
    });

    return finalResult;
  // @flow-weaver-body-end
  return { onSuccess: false, onFailure: true, output: '' };
}
