/**
 * Cross-file workflow: imports node types from separate files.
 * Tests compiler codegen type-safety bugs.
 */

import { parseConfig } from './nodes.js';
import { runTask } from './nodes.js';

// @flow-weaver-runtime-start
// ============================================================================
// DO NOT EDIT - This section is auto-generated by Flow Weaver
// ============================================================================

// ============================================================================
// Runtime Types
// ============================================================================

type TStatusType =
  | "RUNNING"
  | "SCHEDULED"
  | "SUCCEEDED"
  | "FAILED"
  | "CANCELLED"
  | "PENDING";

type TVariableIdentification = {
  nodeTypeName: string;
  id: string;
  scope?: string | undefined;
  side?: "start" | "exit" | undefined;
  portName: string;
  executionIndex: number;
  key?: string | undefined;
};

type TStatusChangedEvent = {
  type: "STATUS_CHANGED";
  nodeTypeName: string;
  id: string;
  scope?: string;
  side?: "start" | "exit";
  executionIndex: number;
  status: TStatusType;
  innerFlowInvocation?: boolean;
};

type TVariableSetEvent = {
  type: "VARIABLE_SET";
  identifier: TVariableIdentification;
  value?: unknown;
  innerFlowInvocation?: boolean;
};

type TErrorLogEvent = {
  type: "LOG_ERROR";
  nodeTypeName: string;
  id: string;
  scope?: string;
  side?: "start" | "exit";
  executionIndex: number;
  error: string;
  code?: string;
  innerFlowInvocation?: boolean;
};

type TWorkflowCompletedEvent = {
  type: "WORKFLOW_COMPLETED";
  executionIndex: number;
  status: "SUCCEEDED" | "FAILED" | "CANCELLED";
  result?: unknown;
  innerFlowInvocation?: boolean;
};

type TEvent =
  | TStatusChangedEvent
  | TVariableSetEvent
  | TErrorLogEvent
  | TWorkflowCompletedEvent;

type TDebugger = {
  sendEvent: (event: TEvent) => void | Promise<void>;
  innerFlowInvocation: boolean;
  sessionId?: string;
};

type TDebugController = {
  beforeNode(nodeId: string, ctx: GeneratedExecutionContext): Promise<void> | void;
  afterNode(nodeId: string, ctx: GeneratedExecutionContext): Promise<void> | void;
};

interface VariableAddress {
  id: string;
  portName: string;
  executionIndex: number;
  nodeTypeName?: string | undefined;
  scope?: string | undefined;
  side?: 'start' | 'exit' | undefined;
  durable?: boolean | undefined;
}

interface ExecutionInfo {
  id: string;
  index: number;
  parentIndex?: number | undefined;
  scopeName?: string | undefined;
}

type DurableGateKind = 'approval' | 'input' | 'agent';
type WireValue = null | boolean | number | string | readonly WireValue[] | { readonly [key: string]: WireValue };
interface WorkflowFrameAddress { workflowId: string; invocation: number; callerNodeId?: string; callerExecutionIndex?: number; }
interface ScopeAddress { parentNodeId: string; parentExecutionIndex: number; scopeName: string; invocation: number; loopIteration?: number; branchArm?: string; }
interface BranchAddress { workflowId: string; frameDepth: number; nodeId: string; executionIndex: number; arm: string; }
interface ExecutionAddress { frames: readonly WorkflowFrameAddress[]; scopes: readonly ScopeAddress[]; branches: readonly BranchAddress[]; nodeId: string; nodeType: string; executionIndex: number; }
interface WorkflowRuntime {
  readonly runId: string;
  readonly abortSignal?: AbortSignal;
  readonly services: { debugger?: TDebugger; debugController?: TDebugController; mocks?: unknown; workflowRegistry?: Readonly<Record<string, (...args: unknown[]) => unknown>>; effectAdapter?: unknown };
  readonly frames: readonly WorkflowFrameAddress[];
  readonly scopes: readonly ScopeAddress[];
  readonly branches: readonly BranchAddress[];
  readonly durable: {
    address(runtime: WorkflowRuntime, nodeId: string, nodeType: string, executionIndex: number): ExecutionAddress;
    shouldExecute(address: ExecutionAddress): boolean;
    commitNode(address: ExecutionAddress): void;
    setVariable(address: ExecutionAddress, portName: string, value: unknown): void;
    getVariable(address: ExecutionAddress, portName: string): unknown;
    resolveGate(runtime: WorkflowRuntime, boundary: { kind: DurableGateKind; nodeId: string; nodeType: string; executionIndex: number; payload: WireValue }): WireValue;
    executeEffect<T extends WireValue>(runtime: WorkflowRuntime, boundary: { nodeId: string; nodeType: string; executionIndex: number }, execute: (operationKey: string) => Promise<{ result: T; receipt: WireValue }>): Promise<T>;
    assertResumeResolutionConsumed(): void;
  };
}

type VariableValue = unknown | (() => unknown) | (() => Promise<unknown>);

// ============================================================================
// Cancellation Error
// ============================================================================

class CancellationError extends Error {
  public readonly executionIndex: number;
  public readonly nodeId?: string;
  public readonly timestamp: number;

  constructor(
    message: string = 'Workflow execution cancelled',
    executionIndex: number = 0,
    nodeId?: string,
    timestamp: number = Date.now()
  ) {
    super(message);
    this.name = 'CancellationError';
    this.executionIndex = executionIndex;
    this.nodeId = nodeId;
    this.timestamp = timestamp;
  }

  static isCancellationError(error: unknown): error is CancellationError {
    return (
      error instanceof CancellationError ||
      (error instanceof Error && error.name === 'CancellationError')
    );
  }
}

// ============================================================================
// Execution Context
// ============================================================================

class GeneratedExecutionContext {
  private variables: Map<string, VariableValue> = new Map();
  private executions: Map<string, ExecutionInfo> = new Map();
  private executionCounter: number = 0;
  private nodeExecutionCounts: Map<string, number> = new Map();
  private isAsync: boolean;
  private flowWeaverDebugger?: TDebugger | undefined;
  private pullExecutors: Map<string, () => void | Promise<void>> = new Map();
  private nodeExecutionIndices: Map<string, number> = new Map();
  private runtime: WorkflowRuntime;
  private scopeInvocationCounts: Map<string, number> = new Map();
  private nestedInvocationCounts: Map<string, number> = new Map();
  private branchStack: BranchAddress[];

  constructor(isAsync: boolean = true, runtime: WorkflowRuntime) {
    this.isAsync = isAsync;
    this.flowWeaverDebugger = runtime.services.debugger;
    this.runtime = runtime;
    this.branchStack = [...runtime.branches];
  }

  registerPullExecutor(id: string, executor: () => void | Promise<void>): void {
    this.pullExecutors.set(id, executor);
  }

  addExecution(id: string, parentIndex?: number, scopeName?: string): number {
    // Use per-node execution counter (each node starts at 0)
    const currentCount = this.nodeExecutionCounts.get(id) || 0;
    const index = currentCount;
    this.nodeExecutionCounts.set(id, currentCount + 1);
    this.executionCounter++;
    this.executions.set(this.getExecutionKey(id, index), {
      id,
      index,
      parentIndex,
      scopeName,
    });
    this.nodeExecutionIndices.set(id, index);
    return index;
  }

  setVariable(address: VariableAddress, value: VariableValue): void | Promise<void> {
    const key = this.getVariableKey(address);
    this.variables.set(key, value);
    if (typeof value !== "function" && address.durable !== false) {
      this.runtime.durable.setVariable(this.executionAddress(address), address.portName, value);
    }
    if (this.flowWeaverDebugger) {
      const actualValue = typeof value === "function" ? value() : value;
      this.sendVariableSetEvent({
        identifier: {
          nodeTypeName: address.nodeTypeName || "unknown",
          id: address.id,
          portName: address.portName,
          executionIndex: address.executionIndex,
          key: "default",
          ...(address.scope && { scope: address.scope }),
          ...(address.side && { side: address.side }),
        },
        value: actualValue,
      });
    }
    return this.isAsync ? Promise.resolve() : undefined;
  }

  getVariable(address: VariableAddress): unknown | Promise<unknown> {
    const executor = this.pullExecutors.get(address.id);
    if (executor) {
      if (!this.hasVariable(address)) {
        const result = executor();
        // Handle async executor (returns Promise)
        if (result instanceof Promise) {
          return result.then(() => {
            const trackedIndex = this.nodeExecutionIndices.get(address.id);
            const finalAddress = trackedIndex !== undefined
              ? { ...address, executionIndex: trackedIndex }
              : address;
            return this.retrieveVariable(finalAddress);
          });
        }
        // Handle sync executor (returns void)
        const trackedIndex = this.nodeExecutionIndices.get(address.id);
        const finalAddress = trackedIndex !== undefined
          ? { ...address, executionIndex: trackedIndex }
          : address;
        return this.retrieveVariable(finalAddress);
      }
    }
    return this.retrieveVariable(address);
  }

  private retrieveVariable(address: VariableAddress): unknown | Promise<unknown> {
    const key = this.getVariableKey(address);
    let value = this.variables.get(key);
    if (!this.variables.has(key)) {
      value = this.runtime.durable.getVariable(this.executionAddress(address), address.portName);
      if (value === undefined) {
        throw new Error(`Variable not found: ${address.id}.${address.portName}[${address.executionIndex}]`);
      }
      this.variables.set(key, value);
    }
    if (typeof value === "function") {
      const result = value();
      if (result instanceof Promise) {
        return result;
      }
      return this.isAsync ? Promise.resolve(result) : result;
    }
    return this.isAsync ? Promise.resolve(value) : value;
  }

  hasVariable(address: VariableAddress): boolean {
    const key = this.getVariableKey(address);
    return this.variables.has(key) || this.runtime.durable.getVariable(this.executionAddress(address), address.portName) !== undefined;
  }

  executionAddress(address: Pick<VariableAddress, "id" | "executionIndex" | "nodeTypeName">): ExecutionAddress {
    const runtime = this.getRuntime();
    return runtime.durable.address(runtime, address.id, address.nodeTypeName ?? address.id, address.executionIndex);
  }

  shouldExecute(nodeId: string, nodeType: string, executionIndex: number): boolean {
    const runtime = this.getRuntime();
    return runtime.durable.shouldExecute(runtime.durable.address(runtime, nodeId, nodeType, executionIndex));
  }

  commitNode(nodeId: string, nodeType: string, executionIndex: number): void {
    const runtime = this.getRuntime();
    runtime.durable.commitNode(runtime.durable.address(runtime, nodeId, nodeType, executionIndex));
  }

  resolveGate(kind: DurableGateKind, nodeId: string, nodeType: string, executionIndex: number, payload: WireValue): WireValue {
    const runtime = this.getRuntime();
    return runtime.durable.resolveGate(runtime, { kind, nodeId, nodeType, executionIndex, payload });
  }

  executeEffect<T extends WireValue>(nodeId: string, nodeType: string, executionIndex: number, execute: (operationKey: string) => Promise<{ result: T; receipt: WireValue }>): Promise<T> {
    const runtime = this.getRuntime();
    return runtime.durable.executeEffect(runtime, { nodeId, nodeType, executionIndex }, execute);
  }

  createNestedRuntime(workflowId: string, callerNodeId: string, callerExecutionIndex: number): WorkflowRuntime {
    const invocation = this.nestedInvocationCounts.get(callerNodeId) ?? 0;
    this.nestedInvocationCounts.set(callerNodeId, invocation + 1);
    const parentRuntime = this.getRuntime();
    return { ...parentRuntime, frames: [...parentRuntime.frames, { workflowId, invocation, callerNodeId, callerExecutionIndex }], scopes: parentRuntime.scopes };
  }

  enterBranch(nodeId: string, executionIndex: number, arm: string): void { const frameDepth = this.runtime.frames.length - 1; const workflowId = this.runtime.frames[frameDepth].workflowId; this.branchStack.push({ workflowId, frameDepth, nodeId, executionIndex, arm }); }
  exitBranch(): void { this.branchStack.pop(); }
  getRuntime(): WorkflowRuntime { return { ...this.runtime, branches: [...this.branchStack] }; }
  forkParallel(): GeneratedExecutionContext {
    const parallelContext = new GeneratedExecutionContext(this.isAsync, this.getRuntime());
    parallelContext.variables = new Map(this.variables);
    parallelContext.executions = new Map(this.executions);
    parallelContext.executionCounter = this.executionCounter;
    parallelContext.pullExecutors = new Map(this.pullExecutors);
    parallelContext.nodeExecutionIndices = new Map(this.nodeExecutionIndices);
    parallelContext.nodeExecutionCounts = new Map(this.nodeExecutionCounts);
    parallelContext.scopeInvocationCounts = new Map(this.scopeInvocationCounts);
    parallelContext.nestedInvocationCounts = new Map(this.nestedInvocationCounts);
    return parallelContext;
  }
  mergeParallel(parallelContext: GeneratedExecutionContext): void {
    this.mergeScope(parallelContext);
    parallelContext.nodeExecutionIndices.forEach((index, id) => { this.nodeExecutionIndices.set(id, index); });
    parallelContext.scopeInvocationCounts.forEach((count, key) => { this.scopeInvocationCounts.set(key, Math.max(this.scopeInvocationCounts.get(key) ?? 0, count)); });
    parallelContext.nestedInvocationCounts.forEach((count, key) => { this.nestedInvocationCounts.set(key, Math.max(this.nestedInvocationCounts.get(key) ?? 0, count)); });
  }

  getExecution(id: string, index: number): ExecutionInfo | undefined {
    return this.executions.get(this.getExecutionKey(id, index));
  }

  createScope(_parentNodeName: string, _parentIndex: number, _scopeName: string, cleanScope: boolean = false, isAsyncOverride?: boolean): GeneratedExecutionContext {
    const effectiveIsAsync = isAsyncOverride !== undefined ? isAsyncOverride : this.isAsync;
    const scopeKey = `${_parentNodeName}:${_parentIndex}:${_scopeName}`;
    const scopeInvocation = this.scopeInvocationCounts.get(scopeKey) ?? 0;
    this.scopeInvocationCounts.set(scopeKey, scopeInvocation + 1);
    const parentRuntime = this.getRuntime();
    const scopedRuntime: WorkflowRuntime = { ...parentRuntime, scopes: [...parentRuntime.scopes, { parentNodeId: _parentNodeName, parentExecutionIndex: _parentIndex, scopeName: _scopeName, invocation: scopeInvocation, loopIteration: scopeInvocation }] };
    const scopedContext = new GeneratedExecutionContext(effectiveIsAsync, scopedRuntime);
    // For per-port function scopes (cleanScope=true), start with empty variables
    // For node-level scopes (cleanScope=false), inherit parent variables
    scopedContext.variables = cleanScope ? new Map() : new Map(this.variables);
    scopedContext.executions = new Map(this.executions);
    scopedContext.executionCounter = this.executionCounter;
    scopedContext.nodeExecutionCounts = new Map(this.nodeExecutionCounts);
    return scopedContext;
  }

  mergeScope(scopedContext: GeneratedExecutionContext): void {
    scopedContext.executions.forEach((info, key) => {
      this.executions.set(key, info);
    });
    scopedContext.variables.forEach((value, key) => {
      this.variables.set(key, value);
    });
    this.executionCounter = Math.max(this.executionCounter, scopedContext.executionCounter);
    scopedContext.nodeExecutionCounts.forEach((count, id) => {
      const currentCount = this.nodeExecutionCounts.get(id) || 0;
      this.nodeExecutionCounts.set(id, Math.max(currentCount, count));
    });
  }

  private getVariableKey(address: VariableAddress): string {
    return `${address.id}:${address.portName}:${address.executionIndex}`;
  }

  private getExecutionKey(id: string, index: number): string {
    return `${id}:${index}`;
  }

  getExecutionCount(): number {
    return this.executionCounter;
  }

  reset(): void {
    this.variables.clear();
    this.executions.clear();
    this.executionCounter = 0;
    this.nodeExecutionCounts.clear();
  }

  isAborted(): boolean {
    return this.runtime.abortSignal?.aborted ?? false;
  }

  getAbortSignal(): AbortSignal | undefined {
    return this.runtime.abortSignal;
  }

  checkAborted(nodeId?: string): void {
    if (this.runtime.abortSignal?.aborted) {
      throw new CancellationError(
        `Workflow execution cancelled${nodeId ? ` at ${nodeId}` : ''}`,
        this.executionCounter,
        nodeId
      );
    }
  }

  async sendStatusChangedEvent(args: {
    nodeTypeName: string;
    id: string;
    scope?: string;
    side?: "start" | "exit";
    executionIndex: number;
    status: TStatusType;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "STATUS_CHANGED",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  private async sendVariableSetEvent(args: {
    identifier: TVariableIdentification;
    value: unknown;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "VARIABLE_SET",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  async sendLogErrorEvent(args: {
    nodeTypeName: string;
    id: string;
    scope?: string;
    side?: "start" | "exit";
    executionIndex: number;
    error: string;
    code?: string;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "LOG_ERROR",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  async sendWorkflowCompletedEvent(args: {
    executionIndex: number;
    status: "SUCCEEDED" | "FAILED" | "CANCELLED";
    result?: unknown;
  }): Promise<void> {
    if (this.flowWeaverDebugger) {
      await this.flowWeaverDebugger.sendEvent({
        type: "WORKFLOW_COMPLETED",
        ...args,
        innerFlowInvocation: this.flowWeaverDebugger.innerFlowInvocation,
      });
    }
  }

  inspectVariables(): Record<string, unknown> {
    const vars: Record<string, unknown> = {};
    for (const [key, value] of this.variables) {
      vars[key] = typeof value === "function" ? "[lazy value]" : value;
    }
    return vars;
  }
}

// @flow-weaver-runtime-end


/**
 * @flowWeaver workflow
 * @node parser parseConfig
 * @node runner runTask
 * @path Start -> parser -> runner -> Exit
 * @connect runner.result -> Exit.output
 * @param execute [order:-1] - Execute
 * @param raw [order:0] - Raw config JSON
 * @returns onSuccess [order:-2] - On Success
 * @returns onFailure [order:-1] - On Failure
 * @returns output [order:0] - Task output string
 */
export async function crossFileWorkflow(execute: boolean, params: { raw: string }, __runtime__: WorkflowRuntime
): Promise<{ onSuccess: boolean; onFailure: boolean; output: string }> {
  // @flow-weaver-body-start
  // ============================================================================
  // DO NOT EDIT - This section is auto-generated by Flow Weaver
  // Edit the @flowWeaver annotations above to modify workflow behavior
  // ============================================================================

    // Recursion depth protection
    const __rd__ = (params as { __rd__?: number }).__rd__ ?? 0;
    if (__rd__ >= 1000) {
      throw new Error('Max recursion depth exceeded (1000) in workflow "crossFileWorkflow"');
    }

    const ctx = new GeneratedExecutionContext(true, __runtime__);

    const __ctrl__: TDebugController = (__runtime__.services.debugController ?? { beforeNode: () => {}, afterNode: () => {} }) as TDebugController;

    const startIdx = ctx.addExecution('Start');
    if (ctx.shouldExecute('Start', 'Start', startIdx)) {
      await ctx.setVariable({ id: 'Start', portName: 'execute', executionIndex: startIdx, nodeTypeName: 'Start' }, execute);
      await ctx.setVariable({ id: 'Start', portName: 'raw', executionIndex: startIdx, nodeTypeName: 'Start' }, params.raw);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'Start',
        id: 'Start',
        executionIndex: startIdx,
        status: 'SUCCEEDED',
      });
      ctx.commitNode('Start', 'Start', startIdx);
    }

    let parserIdx: number | undefined;
    let runnerIdx: number | undefined;
    let parser_success = false;


    await __ctrl__.beforeNode('parser', ctx);

    // ── parser (parseConfig) ──
    ctx.checkAborted('parser');
    parserIdx = ctx.addExecution('parser');
    if (ctx.shouldExecute('parser', 'parseConfig', parserIdx)) {
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'parseConfig',
        id: 'parser',
        executionIndex: parserIdx,
        status: 'RUNNING',
      });

      parser_success = false;

      try {
        await ctx.setVariable({ id: 'parser', portName: 'execute', executionIndex: parserIdx, nodeTypeName: 'parseConfig', durable: false }, true);
        const parser_raw = await ctx.getVariable({ id: 'Start', portName: 'raw', executionIndex: startIdx, nodeTypeName: 'Start' }) as string;
        await ctx.setVariable({ id: 'parser', portName: 'raw', executionIndex: parserIdx, nodeTypeName: 'parseConfig', durable: false }, parser_raw);
        const parserResult = parseConfig(parser_raw);
        const parserResult_raw: unknown = parserResult;
        await ctx.setVariable({ id: 'parser', portName: 'config', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, typeof parserResult_raw === 'object' && parserResult_raw !== null && 'config' in parserResult_raw ? parserResult_raw.config : parserResult_raw);
        await ctx.setVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, true);
        await ctx.setVariable({ id: 'parser', portName: 'onFailure', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, false);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'parseConfig',
          id: 'parser',
          executionIndex: parserIdx,
          status: 'SUCCEEDED',
        });
        ctx.commitNode('parser', 'parseConfig', parserIdx);
        await __ctrl__.afterNode('parser', ctx);
        parser_success = true;
      } catch (error: unknown) {
        if ((error as { code?: unknown })?.code === 'FLOW_WEAVER_DURABLE_GATE_YIELD') throw error;
        const isCancellation = CancellationError.isCancellationError(error);
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'parseConfig',
          id: 'parser',
          executionIndex: parserIdx,
          status: isCancellation ? 'CANCELLED' : 'FAILED',
        });
        if (!isCancellation) {
          ctx.sendLogErrorEvent({
            nodeTypeName: 'parseConfig',
            id: 'parser',
            executionIndex: parserIdx,
            error: error instanceof Error ? error.message : String(error),
            code: typeof (error as { code?: unknown }).code === 'string' ? ((error as { code?: unknown }).code as string) : undefined,
          });
          await ctx.setVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, false);
          await ctx.setVariable({ id: 'parser', portName: 'onFailure', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }, true);
          parser_success = false;
        }
        throw error;
      }
    } else {
      parser_success = await ctx.getVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }) as boolean;
    }

    if (parser_success) {
      await __ctrl__.beforeNode('runner', ctx);

      // ── runner (runTask) ──
      ctx.checkAborted('runner');
      runnerIdx = ctx.addExecution('runner');
      if (ctx.shouldExecute('runner', 'runTask', runnerIdx)) {
        await ctx.sendStatusChangedEvent({
          nodeTypeName: 'runTask',
          id: 'runner',
          executionIndex: runnerIdx,
          status: 'RUNNING',
        });

        try {
          const runner_execute = parserIdx !== undefined ? await ctx.getVariable({ id: 'parser', portName: 'onSuccess', executionIndex: parserIdx, nodeTypeName: 'parseConfig' }) as boolean : false;
          await ctx.setVariable({ id: 'runner', portName: 'execute', executionIndex: runnerIdx, nodeTypeName: 'runTask', durable: false }, runner_execute);
          const runner_config = await ctx.getVariable({ id: 'parser', portName: 'config', executionIndex: parserIdx!, nodeTypeName: 'parseConfig' }) as Parameters<typeof runTask>[1];
          await ctx.setVariable({ id: 'runner', portName: 'config', executionIndex: runnerIdx, nodeTypeName: 'runTask', durable: false }, runner_config);
          const runnerResult = runTask(runner_execute, runner_config);
          await ctx.setVariable({ id: 'runner', portName: 'result', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.result);
          await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.onSuccess);
          await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, runnerResult.onFailure);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'runTask',
            id: 'runner',
            executionIndex: runnerIdx,
            status: 'SUCCEEDED',
          });
          ctx.commitNode('runner', 'runTask', runnerIdx);
          await __ctrl__.afterNode('runner', ctx);
        } catch (error: unknown) {
          if ((error as { code?: unknown })?.code === 'FLOW_WEAVER_DURABLE_GATE_YIELD') throw error;
          const isCancellation = CancellationError.isCancellationError(error);
          await ctx.sendStatusChangedEvent({
            nodeTypeName: 'runTask',
            id: 'runner',
            executionIndex: runnerIdx,
            status: isCancellation ? 'CANCELLED' : 'FAILED',
          });
          if (!isCancellation) {
            ctx.sendLogErrorEvent({
              nodeTypeName: 'runTask',
              id: 'runner',
              executionIndex: runnerIdx,
              error: error instanceof Error ? error.message : String(error),
              code: typeof (error as { code?: unknown }).code === 'string' ? ((error as { code?: unknown }).code as string) : undefined,
            });
            await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
            await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, true);
          }
          throw error;
        }
      } else {
      }

    } else {
      const runnerIdx = ctx.addExecution('runner');
      await ctx.setVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
      await ctx.setVariable({ id: 'runner', portName: 'onFailure', executionIndex: runnerIdx, nodeTypeName: 'runTask' }, false);
      await ctx.sendStatusChangedEvent({
        nodeTypeName: 'runTask',
        id: 'runner',
        executionIndex: runnerIdx,
        status: 'CANCELLED',
      });
    }
    ctx.checkAborted('Exit');
    const exitIdx = ctx.addExecution('Exit');
    const exit_output = runnerIdx !== undefined ? await ctx.getVariable({ id: 'runner', portName: 'result', executionIndex: runnerIdx, nodeTypeName: 'runTask' }) : undefined;
    await ctx.setVariable({ id: 'Exit', portName: 'output', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_output);
    const exit_onSuccess = runnerIdx !== undefined ? await ctx.getVariable({ id: 'runner', portName: 'onSuccess', executionIndex: runnerIdx, nodeTypeName: 'runTask' }) : false;
    await ctx.setVariable({ id: 'Exit', portName: 'onSuccess', executionIndex: exitIdx, nodeTypeName: 'Exit' }, exit_onSuccess);

    await ctx.setVariable({ id: 'Exit', portName: 'onFailure', executionIndex: exitIdx, nodeTypeName: 'Exit' }, false);
    const finalResult = { onSuccess: exit_onSuccess as boolean, onFailure: false, output: exit_output as string };

    await ctx.sendStatusChangedEvent({
      nodeTypeName: 'Exit',
      id: 'Exit',
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
    });
    ctx.sendWorkflowCompletedEvent({
      executionIndex: exitIdx,
      status: 'SUCCEEDED',
      result: finalResult,
    });

    return finalResult;
  // @flow-weaver-body-end
}
