/**
 * Tests for src/cli/commands/compile.ts: displayPath, verbose paths,
 * error handling, strict validation warnings, sourceMap edge cases.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { captureConsole, type ConsoleCapture } from '../../helpers/console-capture';

const TEMP_DIR = path.join(os.tmpdir(), `fw-compile-cov-${process.pid}`);

let out: ConsoleCapture;

beforeEach(() => {
  fs.mkdirSync(TEMP_DIR, { recursive: true });
  out = captureConsole();
});

afterEach(() => {
  out.restore();
  fs.rmSync(TEMP_DIR, { recursive: true, force: true });
});

// Present in a file once compile has written the generated body into it.
const GENERATED_MARKER = 'DO NOT EDIT - This section is auto-generated by Flow Weaver';

function writeFixture(name: string, content: string): string {
  const filePath = path.join(TEMP_DIR, name);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return filePath;
}

const SIMPLE_WORKFLOW = `
/**
 * @flowWeaver nodeType
 */
function proc(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node p proc
 * @connect p.onSuccess -> Exit.onSuccess
 */
export function simpleWf(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;

const FILE_WITH_FLOWWEAVER_BUT_NO_WORKFLOW = `
/**
 * @flowWeaver nodeType
 */
function helperNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}
`;

const FILE_WITH_PARSE_ERRORS = `
/**
 * @flowWeaver nodeType
 */
function realNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node r realNode
 * @node ghost nonExistentType
 * @connect r.onSuccess -> ghost.execute
 * @connect ghost.onSuccess -> Exit.onSuccess
 */
export function brokenWf(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;

describe('compileCommand coverage', () => {
  it('should handle verbose mode with parse warnings and file listing', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('verbose-wf.ts', SIMPLE_WORKFLOW);

    await compileCommand(filePath, { verbose: true });

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('@flowWeaver workflow');
  });

  it('should skip files with @flowWeaver but no workflow (verbose)', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('no-wf.ts', FILE_WITH_FLOWWEAVER_BUT_NO_WORKFLOW);

    // The file has a nodeType but no workflow, so it is skipped, not failed.
    await compileCommand(filePath, { verbose: true });

    expect(out.text()).toContain('skip no-wf.ts (no workflow)');
    expect(out.text()).toContain('0 files compiled');
    expect(fs.readFileSync(filePath, 'utf8')).toBe(FILE_WITH_FLOWWEAVER_BUT_NO_WORKFLOW);
  });

  it('should refuse files that reference an unknown node type', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('parse-err.ts', FILE_WITH_PARSE_ERRORS);

    await expect(compileCommand(filePath, {})).rejects.toThrow('1 file(s) failed to compile');

    expect(out.of('error')).toContain("Node type 'nonExistentType' doesn't exist");
    expect(fs.readFileSync(filePath, 'utf8')).toBe(FILE_WITH_PARSE_ERRORS);
  });

  it('should report no changes in verbose mode when re-compiling stable file', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('stable.ts', SIMPLE_WORKFLOW);

    await compileCommand(filePath, {});
    const compiled = fs.readFileSync(filePath, 'utf8');
    out.restore();
    out = captureConsole();

    // Second compile should report no changes in verbose
    await compileCommand(filePath, { verbose: true });

    expect(out.text()).toMatch(/stable\.ts no changes/);
    expect(fs.readFileSync(filePath, 'utf8')).toBe(compiled);
  });

  it('should show dry-run messages for files with and without changes', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('dryrun.ts', SIMPLE_WORKFLOW);

    // First dry run (has changes)
    await compileCommand(filePath, { dryRun: true });
    const unchanged = fs.readFileSync(filePath, 'utf8');
    expect(unchanged).toBe(SIMPLE_WORKFLOW);

    // Compile for real
    await compileCommand(filePath, {});

    // Second dry run on already-compiled file (no changes)
    await compileCommand(filePath, { dryRun: true });
    expect(out.text()).toMatch(/dryrun\.ts \(no changes, dry run\)/);
  });

  it('should handle directory input expanding to glob', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const dir = path.join(TEMP_DIR, 'dir-expand');
    fs.mkdirSync(dir, { recursive: true });
    const a = writeFixture('dir-expand/a.ts', SIMPLE_WORKFLOW);
    const b = writeFixture('dir-expand/sub/b.ts', SIMPLE_WORKFLOW.replace('simpleWf', 'otherWf'));

    await compileCommand(dir, {});

    expect(fs.readFileSync(a, 'utf8')).toContain(GENERATED_MARKER);
    expect(fs.readFileSync(b, 'utf8')).toContain(GENERATED_MARKER);
    expect(out.text()).toContain('2 files compiled');
  });

  it('should throw for no matching files', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');

    await expect(
      compileCommand(path.join(TEMP_DIR, 'nonexistent-glob-xyz/**/*.ts'), {})
    ).rejects.toThrow(/No files found/);
  });

  it('should handle format auto (default) detection', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('auto-fmt.ts', SIMPLE_WORKFLOW);

    const pkgDir = path.join(TEMP_DIR, 'cjs-project');
    fs.mkdirSync(pkgDir, { recursive: true });
    fs.writeFileSync(path.join(pkgDir, 'package.json'), JSON.stringify({ name: 'x', type: 'commonjs' }));
    const cwd = process.cwd();
    process.chdir(pkgDir);
    try {
      await compileCommand(filePath, { format: 'auto' });
    } finally {
      process.chdir(cwd);
    }

    // auto reads the module format from the package.json in the working directory.
    expect(out.text()).toContain('1 file compiled (CJS)');
    expect(fs.readFileSync(filePath, 'utf8')).toContain(GENERATED_MARKER);
  });

  it('should handle strict mode validation errors and throw', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');

    // A workflow with an invalid port connection, which strict validation catches.
    const badContent = `
/**
 * @flowWeaver nodeType
 */
function goodNode(execute: boolean): { onSuccess: boolean; onFailure: boolean } {
  return { onSuccess: true, onFailure: false };
}

/**
 * @flowWeaver workflow
 * @node g goodNode
 * @node h goodNode
 * @connect g.onSuccess -> h.execute
 * @connect h.onSuccess -> Exit.onSuccess
 * @connect g.nonexistentPort -> h.nonexistentPort
 */
export function strictFailWf(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean }> {
  throw new Error("Not implemented");
}
`;
    const filePath = writeFixture('strict-fail.ts', badContent);

    await expect(compileCommand(filePath, { strict: true })).rejects.toThrow(/failed/i);
  });

  it('should handle sourceMap with verbose mode', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('srcmap-v.ts', SIMPLE_WORKFLOW);

    await compileCommand(filePath, { sourceMap: true, verbose: true });

    expect(fs.existsSync(filePath + '.map')).toBe(true);
  });

  it('should not duplicate sourceMappingURL on re-compile with sourceMap', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('srcmap-dup.ts', SIMPLE_WORKFLOW);

    await compileCommand(filePath, { sourceMap: true });
    const first = fs.readFileSync(filePath, 'utf8');
    const count1 = (first.match(/sourceMappingURL/g) || []).length;

    // Re-compile
    await compileCommand(filePath, { sourceMap: true });
    const second = fs.readFileSync(filePath, 'utf8');
    const count2 = (second.match(/sourceMappingURL/g) || []).length;

    // Should not add duplicate
    expect(count2).toBeLessThanOrEqual(count1);
  });

  it('should report summary with format note when not verbose', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('summary.ts', SIMPLE_WORKFLOW);

    await compileCommand(filePath, { verbose: false, format: 'esm' });

    expect(out.text()).toMatch(/1 file compiled \(ESM\) in /);
  });

  it('should handle singular file count in summary', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('single.ts', SIMPLE_WORKFLOW);

    // One file = "1 file compiled" (singular)
    await compileCommand(filePath, {});

    expect(out.text()).toMatch(/ 1 file compiled/);
    expect(out.text()).not.toContain('1 files compiled');
  });

  it('should compile in strict mode and show warnings with fix hints when verbose', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    const filePath = writeFixture('strict-warn.ts', SIMPLE_WORKFLOW);

    // Strict promotes type coercions only; the missing Start connection stays a warning.
    await compileCommand(filePath, { strict: true, verbose: true });

    expect(out.of('warn')).toContain('No Start Connections');
    expect(out.of('warn')).toContain('How to fix:');
    expect(fs.readFileSync(filePath, 'utf8')).toContain(GENERATED_MARKER);
  });
});

describe('displayPath coverage', () => {
  it('should return absolute path when relative would escape cwd', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');

    // The file is in the temp dir, outside cwd, so it is shown by absolute path.
    const filePath = writeFixture('abs-path.ts', SIMPLE_WORKFLOW);
    await compileCommand(filePath, { verbose: true });

    expect(out.text()).toContain(`  ${filePath}`);
    expect(out.text()).not.toContain('..');
  });

  it('should return a relative path for a file under cwd', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');
    // realpath: on macOS the temp dir is reached through a symlink, and
    // process.cwd() reports the resolved path.
    const filePath = fs.realpathSync(writeFixture('rel/rel-path.ts', SIMPLE_WORKFLOW));
    const cwd = process.cwd();
    process.chdir(fs.realpathSync(TEMP_DIR));
    try {
      await compileCommand(filePath, { verbose: true });
    } finally {
      process.chdir(cwd);
    }

    expect(out.text()).toContain(`  ${path.join('rel', 'rel-path.ts')}`);
    expect(out.text()).not.toContain(filePath);
  });

  it('should show validation warnings in default (non-strict) compile mode', async () => {
    const { compileCommand } = await import('../../../src/cli/commands/compile');

    // Workflow with a node that has an unused output port (triggers UNUSED_OUTPUT_PORT warning)
    const workflowWithWarning = `
/**
 * @flowWeaver nodeType
 * @input value
 * @output result
 * @output extra
 */
function dataNode(execute: boolean, value: number): { onSuccess: boolean; onFailure: boolean; result: number; extra: string } {
  if (!execute) return { onSuccess: false, onFailure: false, result: 0, extra: '' };
  return { onSuccess: true, onFailure: false, result: value * 2, extra: 'unused' };
}

/**
 * @flowWeaver workflow
 * @node d dataNode [expr: value="42"]
 * @connect d.result -> Exit.output
 * @path Start -> d -> Exit
 * @returns output
 */
export async function warningWorkflow(execute: boolean): Promise<{ onSuccess: boolean; onFailure: boolean; output: number }> {
  // @flow-weaver-body-start
  throw new Error('Not implemented');
  // @flow-weaver-body-end
}
`;
    const filePath = writeFixture('warn-default.ts', workflowWithWarning);

    // Spy on logger.warn to capture warnings
    const { logger } = await import('../../../src/cli/utils/logger');
    const warnSpy = vi.spyOn(logger, 'warn');

    // Compile WITHOUT --strict - should still show warnings
    await compileCommand(filePath, {});

    // Check that at least one warning was logged (e.g. UNUSED_OUTPUT_PORT for "extra")
    const warnCalls = warnSpy.mock.calls.map(c => String(c[0]));
    const hasValidationWarning = warnCalls.some(
      (msg) => msg.includes('extra') || msg.includes('UNUSED') || msg.includes('never connected')
    );
    expect(hasValidationWarning).toBe(true);

    warnSpy.mockRestore();
  });
});
