#!/usr/bin/env tsx
/**
 * Generates src/generated-version.ts from package.json version.
 * Run as a prebuild step so tsc can compile it without runtime requires.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkgPath = path.resolve(__dirname, '..', 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

const outPath = path.resolve(__dirname, '..', 'src', 'generated-version.ts');
const content = `// Auto-generated by scripts/generate-version.ts — do not edit manually
export const VERSION = '${pkg.version}';\n`;

fs.writeFileSync(outPath, content, 'utf-8');
console.log(`Generated src/generated-version.ts (v${pkg.version})`);
