#!/usr/bin/env tsx
/**
 * Generates src/api/inline-engine.generated.ts: the durable engine's source,
 * as one string, ready to be copied into every compiled workflow file.
 *
 * The engine (`src/runtime/continuation-core.ts` and
 * `src/runtime/durable-execution.ts`) is the package's own implementation;
 * the same text runs inside compiled files, so there is one engine and it
 * cannot drift. This script strips the module syntax (imports, `export`)
 * and leaves the declarations. `generateInlineRuntime` prepends what the
 * imports provided (the version, three host types) and appends the exports
 * a compiled file offers.
 *
 * Run as a prebuild step, like generate-version. The output is gitignored.
 *
 *   tsx scripts/generate-inline-engine.ts
 *   tsx scripts/generate-inline-engine.ts --check
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SOURCES = ['src/runtime/continuation-core.ts', 'src/runtime/durable-execution.ts'];
const OUTPUT = path.join(ROOT, 'src', 'api', 'inline-engine.generated.ts');

/** Drop import statements and `export` modifiers; keep everything else verbatim. */
export function inlineEngineSource(files: ReadonlyArray<{ readonly name: string; readonly text: string }>): string {
  return files
    .map(({ name, text }) => {
      const body = text
        // `import { a, b } from '...';` and `import type ... ;`, possibly multi-line.
        .replace(/^import[\s\S]*?from\s+["'][^"']+["'];[ \t]*\n/gm, '')
        // `export const|function|class|interface|type|declare` → the declaration itself.
        .replace(/^export\s+(?=(?:const|let|function|async\s+function|class|abstract\s+class|interface|type|declare|enum)\b)/gm, '')
        // A leading file comment describes the module; the section header below does that here.
        .replace(/^\/\*\*[\s\S]*?\*\/\n/, '')
        // Doc comments become plain block comments: the prose stays for a reader of the
        // compiled file, and nothing that scans a workflow file for JSDoc sees the engine.
        .replace(/^(\s*)\/\*\*(?!\/)/gm, '$1/*')
        .trimStart();
      const header = `// ---- ${name} ${'-'.repeat(Math.max(4, 74 - name.length))}`;
      return `${header}\n\n${body.trimEnd()}\n`;
    })
    .join('\n');
}

export function renderModule(source: string): string {
  return [
    '// Auto-generated by scripts/generate-inline-engine.ts — do not edit manually.',
    '// The durable engine as text, for src/api/inline-runtime.ts to copy into compiled files.',
    `export const INLINE_ENGINE_SOURCE = ${JSON.stringify(source)};`,
    '',
  ].join('\n');
}

// Always a script, never imported (like generate-version.ts), so no
// "am I main" check: comparing argv[1] with import.meta.url is a drive-letter
// case away from being wrong on Windows, and a silent no-op there would
// fail the build with a missing module.
const files = SOURCES.map((file) => ({ name: file, text: fs.readFileSync(path.join(ROOT, file), 'utf8') }));
const rendered = renderModule(inlineEngineSource(files));
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
  if (current !== rendered) {
    console.error('src/api/inline-engine.generated.ts is stale; run: npx tsx scripts/generate-inline-engine.ts');
    process.exit(1);
  }
  console.log('inline engine is up to date');
} else {
  fs.writeFileSync(OUTPUT, rendered, 'utf8');
  console.log(`Generated src/api/inline-engine.generated.ts (${rendered.length} bytes from ${SOURCES.length} files)`);
}
