/**
 * The text transform behind scripts/generate-inline-engine.ts, apart from
 * the script so it can be tested: importing the script runs it.
 */
/** Drop import statements and `export` modifiers, and keep everything else verbatim. */
export function inlineEngineSource(files: ReadonlyArray<{ readonly name: string; readonly text: string }>): string {
  return files
    .map(({ name, text }) => {
      // Every pattern below, and the development-region markers that
      // src/api/inline-runtime.ts finds later, expect LF. A Windows checkout
      // has CRLF.
      const body = text
        .replace(/\r\n/g, '\n')
        // An import line such as `import { a, b } from '...'` or `import type ...`, possibly multi-line.
        .replace(/^import[\s\S]*?from\s+["'][^"']+["'];[ \t]*\n/gm, '')
        // `export const|function|class|interface|type|declare` → the declaration itself.
        .replace(/^export\s+(?=(?:const|let|function|async\s+function|class|abstract\s+class|interface|type|declare|enum)\b)/gm, '')
        // A leading file comment describes the module, a job the section header below already does here.
        .replace(/^\/\*\*[\s\S]*?\*\/\n/, '')
        // Doc comments become plain block comments: the prose stays for a reader of the
        // compiled file, and nothing that scans a workflow file for JSDoc sees the engine.
        .replace(/^(\s*)\/\*\*(?!\/)/gm, '$1/*')
        .trimStart();
      const header = `// ---- ${name} ${'-'.repeat(Math.max(4, 74 - name.length))}`;
      return `${header}\n\n${body.trimEnd()}\n`;
    })
    .join('\n');
}

export function renderModule(engine: string, context: string): string {
  return [
    '// Auto-generated by scripts/generate-inline-engine.ts. Do not edit manually.',
    '// The durable engine and the execution context as text, for src/api/inline-runtime.ts',
    '// to copy into compiled files.',
    `export const INLINE_ENGINE_SOURCE = ${JSON.stringify(engine)};`,
    `export const INLINE_EXECUTION_CONTEXT_SOURCE = ${JSON.stringify(context)};`,
    '',
  ].join('\n');
}
