/**
 * Configurable branding for generated output.
 *
 * The library ships with generic defaults. The root project (app/CLI)
 * calls {@link configureGeneratedBranding} at startup to inject
 * organisation-specific values (URLs, attribution text, etc.).
 */

export interface GeneratedBranding {
  /** Single-line comment placed at the top of generated code files */
  header: (command?: string) => string;
  /** Markdown attribution line for generated documentation */
  markdown: string;
}

const WEBSITE_URL = 'https://flowweaver.ai';

const DEFAULT: GeneratedBranding = {
  header: (cmd) =>
    cmd
      ? `// Generated by Flow Weaver (${WEBSITE_URL}) — ${cmd}`
      : `// Generated by Flow Weaver (${WEBSITE_URL})`,
  markdown: `*Generated by [Flow Weaver](${WEBSITE_URL})*`,
};

let _branding: GeneratedBranding = DEFAULT;

export function configureGeneratedBranding(branding: GeneratedBranding): void {
  _branding = branding;
}

export function getGeneratedBranding(): GeneratedBranding {
  return _branding;
}
